version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"

volumes:
  pgdata:
    # Este volumen se utiliza para persistir los datos de la base de datos PostgreSQL.
    # Docker almacenará los datos de la base de datos en una ubicación persistente en el sistema de archivos del host.
