INSERT INTO autores (nombre) VALUES
('J. K. Rowling'),
('Homero'),
('Jane Austen'),
('Stephen King');

INSERT INTO generos (nombre) VALUES
('Romance'),
('Aventuras'),
('Fantasía'),
('Ciencia ficción'),
('Terror'),
('Comedia'),
('Suspense'),
('Arte y literatura');

INSERT INTO audiolibros (titulo, autor, descripcion, img) VALUES
('Harry Potter y la piedra filosofal', 1, '«Con las manos temblorosas, Harry le dio la vuelta al sobre y vio un sello de lacre púrpura con un escudo de armas: un león, un águila, un tejón y una serpiente, que rodeaban una gran letra H.»
Harry Potter nunca ha oído hablar de Hogwarts hasta que empiezan a caer cartas en el felpudo del número 4 de Privet Drive. Llevan la dirección escrita con tinta verde en un sobre de pergamino amarillento con un sello de lacre púrpura, y sus horripilantes tíos se apresuran a confiscarlas. Más tarde, el día que Harry cumple once años, Rubeus Hagrid, un hombre gigantesco cuyos ojos brillan como escarabajos negros, irrumpe con una noticia extraordinaria: Harry Potter es un mago, y le han concedido una plaza en el Colegio Hogwarts de Magia y Hechicería. ¡Está a punto de comenzar una aventura increíble!', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HarryPotter1.jpeg'),
('La Odisea', 2, 'Este poema épico, compuesto por veinticuatro cantos, narra la vuelta a casa, tras una década de guerra, del héroe griego Odiseo (Ulises, en latín). Para el regreso a Itaca, su hogar y su reino, y tras una ofensa al dios Poseidón, Odiseo dedica otros diez años, condenado a navegar sin rumbo sufriendo diversas vicisitudes.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaOdisea.png'),
('Orgullo y Prejuicio', 3, '«Es una verdad universalmente aceptada que todo soltero en posesión de una gran fortuna necesita una esposa ». Nueva traducción ilustrada de la novela de Jane Austen. Este comienzo, que, junto con el de Ana Karénina, es quizás uno de los más famosos de la historia de la literatura, nos introduce sabiamente en el mundo de Jane Austen y de su novela más emblemática. Orgullo y prejuicio, publicada en 1813 tras el éxito de Juicio y sentimiento, reúne de forma ejemplar sus temas recurrentes y su visión inimitable en la historia de las cinco hijas de la señora Bennett, que no tiene otro objetivo en su vida que conseguir una buena boda para todas ellas. Dos ricos jóvenes, el señor Bingley y el señor Darcy, aparecen en su punto de mira e inmediatamente se ven señalados como posibles  presas . De hecho, la relación entre la hija mayor, Jane, y el señor Bingley parece muy prometedora pero, por influencia del arrogante señor Darcy, se frustran todas las esperanzas. La intervención de Elizabeth, la hija segunda, perspicaz, consciente de su valor, y algo rebelde, determinará el rumbo de la novela. En ella el opresivo ambiente de la familia, la presión del matrimonio, la diferencia de clases, el fantasma de la pobreza y la delicada sensibilidad de una heroína decidida, pero no libre de errores de juicio y dudas de comportamiento, se conjugan para crear una obra maestra leída a lo largo de más de dos siglos.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/OrgulloYPrejuicio.jpg'),
('El Coco', 4, 'La estudiante de secundaria Sadie Harper (Sophie Tatcher) y su hermana menor Sawyer (Vivien Lyra Blair) se están recuperando de la reciente muerte de su madre y no reciben mucho apoyo de su padre, Will (Chris Messina), un terapeuta que está lidiando con su propio dolor.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElCoco.jpg'),
('El Hombre Del Traje Negro', 4, 'A los 90 años y antes de que le llegue la muerte, Gary decide poner por escrito lo que le sucedió en 1914, cuando sólo tenía 9, para que quede constancia. Un encuentro paranormal con un hombre con un traje negro de tres piezas mientras pescaba truchas en la orilla de un solitario río.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElHombreDelTrajeNegro.jpg'),
('Popsy', 4, 'Sheridan es un adicto al juego quien ha contraído una enorme deuda. Para pagarla, secuestra a niños a petición de un mafioso. El niño que secuestra resulta ser un vampiro al igual que su Abuelito (Popsy en inglés) que no esta dispuesto a dejar que Sheridan huya con su nieto.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Popsy.jpg'),
('Un Trago De Despedida', 4, 'Cierta noche de invierno, en un bar, varios parroquianos mantienen sus charlas habituales. Cuando están a punto de cerrar, un hombre muy alarmado entra pidiendo ayuda: su coche ha quedado atrapado por la nieve en la carretera que conduce a Jerusalem’s Lot (o Salem’s lot), un pueblo «aparentemente» abandonado.
Lo que sobrecoge a esos parroquianos es que la mujer y la hija del conductor han quedado en el interior del vehículo. Inmediatamente se ponen en marcha, aunque quizá cuando lleguen sea tarde.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElUmbralDeLaNoche.jpg');

INSERT INTO genero_audiolibro (audiolibro, genero) VALUES
(3, 1),
(1, 3),
(4, 5),
(5, 5),
(6, 5),
(7, 5),
(2, 8);

INSERT INTO capitulos (numero, nombre, audiolibro, audio) VALUES
(1, 'El niño que sobrevivió', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_1.mp3'),
(2, 'El vidrio que se desvaneció', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_2.mp3'),
(3, 'Las cartas de nadie', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_3.mp3mp3'),
(4, 'El guardián de las llaves', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_4.mp3'),
(5, 'El callejón Diagon', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_5.mp3'),
(6, 'El viaje a través del andén nueve y tres cuartos', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_6.mp3'),
(7, 'El Sombrero Seleccionador', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_7.mp3'),
(8, 'El profesor de Pociones', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_8.mp3'),
(9, 'El duelo a medianoche', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_9.mp3'),
(10, 'Halloween', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_10.mp3'),
(11, 'Quidditch', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_11.mp3'),
(12, 'El espejo de Oesed', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_12.mp3'),
(13, 'Nicolás Flamel', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_13.mp3'),
(14, 'Norberto, el ridgeback noruego', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_14.mp3'),
(15, 'El bosque prohibido', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_15.mp3'),
(16, 'A través de la trampilla', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_16.mp3'),
(17, 'El hombre con dos caras', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_17.mp3'),
(1, 'Canto 01: Concilio de los dioses. Exhortación de Atenea a Telémaco', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_1.mp3'),
(2, 'Canto 02: Telémaco reúne en asamblea al pueblo de Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_2.mp3'),
(3, 'Canto 03: Telémaco viaja a Pilos para informarse sobre su padre', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_3.mp3'),
(4, 'Canto 04: Telémaco viaja a Esparta para informarse sobre su padre', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_4.mp3'),
(5, 'Canto 05: Ulises llega a Esqueria de los feacios', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_5.mp3'),
(6, 'Canto 06: Ulises y Nausícaa', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_6.mp3'),
(7, 'Canto 07: Ulises en el palacio de Alcínoo', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_7.m4a'),
(8, 'Canto 08: Ulises agasajado por los feacios', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_8.mp3'),
(9, 'Canto 09: Ulises cuenta sus aventuras: los cicones, los lotófagos, los cíclopes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_9.mp3'),
(10, 'Canto 10: La isla de Eolo. El palacio de Circe la hechicera', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_10.mp3'),
(11, 'Canto 11: Descenso al Hades', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_11.mp3'),
(12, 'Canto 12: Las sirenas. Escila y Caribdis. La Isla de Helios. Ogigia.', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_12.mp3'),
(13, 'Canto 13: Los feacios despiden a Ulises. Llegada a Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_13.mp3'),
(14, 'Canto 14: Ulises en la majada de Eumeo', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_14.m4a'),
(15, 'Canto 15: Telémaco regresa a Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_15.m4a'),
(16, 'Canto 16: Telémaco reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_16.mp3'),
(17, 'Canto 17: Ulises mendiga entre los pretendientes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_17.mp3'),
(18, 'Canto 18: Los pretendientes vejan a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_18.mp3'),
(19, 'Canto 19: La esclava Euriclea reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_19.mp3'),
(20, 'Canto 20: La última cena de los pretendientes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_20.mp3'),
(21, 'Canto 21: El certamen del arco', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_21.m4a'),
(22, 'Canto 22: La venganza', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_22.mp3'),
(23, 'Canto 23: Penélope reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_23.mp3'),
(24, 'Canto 24. El pacto', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_24.mp3'),
(1, 'Capítulo 1', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_1.mp3'),
(2, 'Capítulo 2', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_2.mp3'),
(3, 'Capítulo 3', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_3.mp3'),
(4, 'Capítulo 4', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_4.mp3'),
(5, 'Capítulo 5', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_5.mp3'),
(6, 'Capítulo 6', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_6.mp3'),
(7, 'Capítulo 7', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_7.mp3'),
(8, 'Capítulo 8', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_8.mp3'),
(9, 'Capítulo 9', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_9.mp3'),
(10, 'Capítulo 10', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_10.mp3'),
(11, 'Capítulo 11', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_11.mp3'),
(12, 'Capítulo 12', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_12.mp3'),
(13, 'Capítulo 13', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_13.mp3'),
(14, 'Capítulo 14', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_14.mp3'),
(15, 'Capítulo 15', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_15.mp3'),
(16, 'Capítulo 16', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_16.mp3'),
(17, 'Capítulo 17', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_17.mp3'),
(18, 'Capítulo 18', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_18.mp3'),
(19, 'Capítulo 19', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_19.mp3'),
(20, 'Capítulo 20', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_20.mp3'),
(21, 'Capítulo 21', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_21.mp3'),
(22, 'Capítulo 22', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_22.mp3'),
(23, 'Capítulo 23', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_23.mp3'),
(24, 'Capítulo 24', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_24.mp3'),
(25, 'Capítulo 25', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_25.mp3'),
(26, 'Capítulo 26', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_26.mp3'),
(27, 'Capítulo 27', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_27.mp3'),
(28, 'Capítulo 28', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_28.mp3'),
(29, 'Capítulo 29', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_29.mp3'),
(30, 'Capítulo 30', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_30.mp3'),
(31, 'Capítulo 31', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_31.mp3'),
(32, 'Capítulo 32', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_32.mp3'),
(33, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_33.mp3'),
(34, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_34.mp3'),
(35, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_35.mp3'),
(36, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_36.mp3'),
(37, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_37.mp3'),
(38, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_38.mp3'),
(39, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_39.mp3'),
(40, 'Capítulo 40', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_40.mp3'),
(41, 'Capítulo 41', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_41.mp3'),
(42, 'Capítulo 42', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_42.mp3'),
(43, 'Capítulo 43', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_43.mp3'),
(44, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_44.mp3'),
(45, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_45.mp3'),
(46, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_46.mp3'),
(47, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_47.mp3'),
(48, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_48.mp3'),
(49, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_49.mp3'),
(50, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_50.mp3'),
(51, 'Capítulo 40', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_51.mp3'),
(52, 'Capítulo 41', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_52.mp3'),
(53, 'Capítulo 42', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_53.mp3'),
(54, 'Capítulo 43', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_54.mp3'),
(55, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_55.mp3'),
(56, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_56.mp3'),
(57, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_57.mp3'),
(58, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_58.mp3'),
(59, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_59.mp3'),
(60, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_60.mp3'),
(61, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_61.mp3'),
(1, 'El Coco', 4, 'https://narrativesarchivos.blob.core.windows.net/audios/ElCoco.mp3'),
(1, 'El Hombre Del Traje Negro', 5, 'https://narrativesarchivos.blob.core.windows.net/audios/ElHombreDelTrajeNegro.mp3'),
(1, 'Popsy', 6, 'https://narrativesarchivos.blob.core.windows.net/audios/Popsy.mp3'),
(1, 'Un Trago De Despedida', 7, 'https://narrativesarchivos.blob.core.windows.net/audios/UnTragoDeDespedida.mp3');
