INSERT INTO autores (nombre, ciudadNacimiento, informacion) VALUES
('Anónimo', 'null', 'null'),
('J. K. Rowling', 'Yate, Gloucestershire, Reino Unido', 'Joanne Rowling (31 de julio de 1965), quien escribe bajo los seudónimos de J. K. Rowling y Robert Galbraith, es una escritora, productora de cine y guionista británica, conocida por ser la autora de la serie de libros Harry Potter, que han superado los quinientos millones de ejemplares vendidos.'),
('Homero', 'null', 'Homero (en griego homérico, Ὅμηρος Hómērŏs; en griego moderno, Όμηρος [Hómirŏs]; en latín, Homerus; ca. siglo VIII a. C.) es el nombre dado al aedo a quien tradicionalmente se atribuye la autoría de los principales poemas épicos griegos: la Ilíada y la Odisea. Desde el período helenístico se ha cuestionado que el autor de ambas obras fuera la misma persona; sin embargo, antes no solo no existían estas dudas, sino que la Ilíada y la Odisea eran considerados relatos históricos reales.'),
('Jane Austen', 'Winchester, Inglaterra', 'Jane Austen (18 de julio de 1817) fue una novelista británica que vivió durante la época georgiana. La ironía que empleaba para dotar de comicidad a sus novelas hace que Jane Austen sea considerada entre los clásicos de la novela inglesa, a la vez que su recepción va, incluso en la actualidad, más allá del interés académico, siendo sus obras leídas por un público más amplio.'),
('Stephen King', 'Portland Maine, Estados Unidos', 'Stephen Edwin King (21 de septiembre de 1947), más conocido como Stephen King y ocasionalmente por su pseudónimo Richard Bachman, es un escritor estadounidense de novelas de terror, ficción sobrenatural, misterio, ciencia ficción y literatura fantástica. Sus libros han vendido más de 500 millones de ejemplares, y en su mayoría han sido adaptados al cine y a la televisión. Ha publicado 65 novelas, once colecciones de relatos y novelas cortas, y siete libros de no ficción, además de un guion cinematográfico, entre otras obras.'),
('Agatha Christie', 'Torquay, Devon, Reino Unido de Gran Bretaña e Irlanda', 'Agatha Mary Clarissa Miller (15 de septiembre de 1890), conocida como Agatha Christie, fue una escritora y dramaturga británica especializada en el género policial, por cuyo trabajo obtuvo reconocimiento a nivel internacional. A lo largo de su carrera, publicó 66 novelas policiales, 6 novelas rosas y 14 cuentos —con el pseudónimo de Mary Westmacott—, además de incursionar como autora teatral en obras como La ratonera o Testigo de cargo.'),
('Arthur Conan Doyle', 'Edimburgo, Escocia, Reino Unido', 'Arthur Ignatius Conan Doyle (22 de mayo de 1859) fue un escritor y médico británico de ascendencia irlandesa, creador del célebre detective de ficción Sherlock Holmes. Fue un autor prolífico cuya obra incluye relatos de ciencia ficción, novela histórica, teatro y poesía.'),
('Charles Perrault', 'París, Reino de Francia', 'Charles Perrault (12 de enero de 1628) fue un escritor francés, principalmente reconocido por haber dado forma literaria a cuentos clásicos infantiles como Piel de asno, Pulgarcito, Barba Azul, La Cenicienta, La bella durmiente, Caperucita Roja y El Gato con Botas, atemperando en muchos casos la crudeza de las versiones orales, la mayoría de sus cuentos son infantiles y de fantasía.'),
('Hermanos Grimm', 'Hanau, Hesse, Alemania', 'Los hermanos Grimm, Jacob Grimm (4 de enero de 1785) y Wilhelm Grimm (22 de febrero de 1786), fueron eruditos, filólogos, mitólogos, investigadores culturales, lexicógrafos y escritores alemanes que coleccionaron y publicaron juntos folclore y libros durante el siglo xix. Están entre los primeros y más conocidos coleccionistas de cuentos porque popularizaron relatos orales tradicionales como La Cenicienta, El príncipe rana, La pastora de ocas, Hansel y Gretel, Rapunzel, Rumpelstiltskin, La bella durmiente y Blancanieves.'),
('Oscar Wilde', 'Dublín, Irlanda, Reino Unido', 'Oscar Fingal OFlahertie Wills Wilde (16 de octubre de 1854), conocido como Oscar Wilde, fue un escritor, poeta y dramaturgo de origen irlandés. Wilde es considerado uno de los dramaturgos más destacados del Londres victoriano tardío. Además, fue una celebridad de la época debido a su gran y aguzado ingenio. Hoy en día, es recordado por sus epigramas, sus cuentos, sus obras de teatro, su única novela, El retrato de Dorian Gray, y la tragedia de su encarcelamiento, seguida de su muerte prematura.'),
('Hans Christian Andersen', 'Odense, Dinamarca', 'Hans Christian Andersen (2 de abril de 1805) fue un escritor y poeta danés famoso por sus cuentos para niños ilustrados por Vilhelm Pedersen. Hijo de un humilde zapatero, pronto aprendió diversos oficios; pero no finalizó ninguno. Con catorce años, huyó con poco dinero a Copenhague dispuesto a hacer fortuna como actor y cantante; escribió algunas obras y después de privaciones y desengaños, consiguió despertar el interés de personalidades del país que se ocuparon de su formación. Andersen siempre sintió que su origen humilde era un lastre y fantaseaba que era el hijo ilegítimo de un gran señor.'),
('Morihei Ueshiba', 'Tanabe, Japón', 'Morihei Ueshiba (1883-1969), en japonés 植芝 盛平, fue un artista marcial japonés de renombre, fundador del arte marcial Aikido. Los practicantes de este arte o aikidōkas también lo llaman Ō-sensei (Gran Maestro) en señal de admiración y respeto'),
('James Redfield', 'Birmingham, Estados Unidos', 'James Redfield (1950) es un escritor, profesor, guionista y productor de cine estadounidense.'),
('Louise L. Hay', 'Los Ángeles, California, Estados Unidos de América', 'Louise Lynn Hay (8 de octubre de 1926) fue una escritora y oradora estadounidense, considerada una de las figuras más representativas del movimiento del Nuevo Pensamiento y una precursora de los libros de autoayuda.'),
('Wallace D. Wattles', 'Illinois, Estados Unidos', 'Wallace Delois Wattles (1860 - 1911) fue un escritor estadounidense, y uno de los más conocidos exponentes del Nuevo Pensamiento, a la par de nombres como William Walker Atkinson, Orison Swett Marden, los esposos Towne (Elizabeth y William) y Ralph Waldo Emerson.'),
('Eckhart Tolle', 'Lünen, Alemania', 'Eckhart Tolle (16 de febrero de 1948) es un guía espiritual y escritor alemán, reconocido por títulos como El poder del Ahora y Un nuevo mundo, ahora. En 2008 un escritor del New York Times lo calificó como "el autor espiritual más popular del país", al igual que la Watkins Review de Londres en 2011. Reside en Vancouver (Canadá) con su mujer, Kim Eng.'),
('Wayne W. Dyer', 'Detroit, Míchigan, Estados Unidos', 'Wayne Walter Dyer (10 de mayo de 1940) fue un psicólogo y escritor de libros de autoayuda estadounidense.'),
('Francisco de Quevedo', 'Madrid, España', 'Francisco Gómez de Quevedo Villegas y Santibáñez Cevallos (14 de septiembre de 1580) fue un noble, político y escritor español del Siglo de Oro. Fue caballero de la Orden de Santiago a partir de 1618 y señor de Torre de Juan Abad a partir de 1620. Junto con Luis de Góngora, con quien mantuvo una enemistad durante toda su vida, es reconocido como uno de los más notables poetas de la literatura española. Además de su poesía, fue un prolífico escritor de narrativa y teatro, así como de textos filosóficos y humanísticos.'),
('Luis de Góngora', 'Córdoba, Corona de Castilla', 'Luis de Góngora y Argote (11 de julio de 1561) fue un poeta y dramaturgo español del Siglo de Oro, máximo exponente de la corriente literaria conocida más tarde como culteranismo o gongorismo.'),
('Elizabeth Hoyt', 'Nueva Orleans, Luisiana, Estados Unidos', 'Elizabeth Hoyt (21 de noviembre de 1970) es el seudónimo de Nancy M. Finney. Hoyt es una de los autoras de novelas históricas más vendidos del New York Times. También escribe novelas románticas contemporáneas bajo el nombre de Julia Harper. Vive en el centro de Illinois con su marido y sus dos hijos.'),
('Meagan McKinney', 'Estados Unidos', 'Meagan McKinney (nacida en 1961) es el seudónimo escogido por la autora americana Ruth Goodman para firmar parte de su obra literaria. Goodman estudió Biología, campo al que se dedicó varios años. Tras el éxito de sus primeras novelas, Goodman decidió dedicarse por completo a la literatura a partir de los años 90 bajo el nombre de McKinney, con el que ha publicado desde entonces más de veinte novelas.'),
('Elizabeth Lowell', 'Milwaukee , Wisconsin , Estados Unidos', 'Ann Maxwell (nacida el 5 de abril de 1944), también conocida como AE Maxwell y Elizabeth Lowell , es una escritora estadounidense. Ha escrito individualmente y con el coautor y esposo Evan más de 50 novelas y un libro de no ficción. Sus novelas van desde la ciencia ficción hasta la ficción histórica, y desde el romance hasta el misterio y el suspenso.'),
('Alexandra Bracken', 'Phoenix, Arizona, Estados Unidos', 'Alexandra Bracken nació en Phoenix, Arizona. Regresó allí tras vivir en Nueva York donde trabajó en la industria editorial, primero como ayudante y luego en marketing. Estudió en La Universidad de William y Mary en Williamsburg, Virginia, graduándose magna cum laude con un grado en Historia e Inglés en mayo de 2009'),
('C. S. Lewis', 'Belfast, Reino Unido de Gran Bretaña e Irlanda', 'Clive Staples Lewis (29 de noviembre de 1898), popularmente conocido como C. S. Lewis, fue un apologista cristiano anglicano, medievalista, y escritor británico, reconocido por sus obras de ficción, especialmente por su saga Las crónicas de Narnia. También fue crítico literario, académico de la universidad de Oxford en el Magdalen College y locutor de radio norirlandés. Lewis fue un amigo cercano de J. R. R. Tolkien, el autor de El Señor de los Anillos.');

INSERT INTO generos (nombre) VALUES
('Romance'),
('Aventuras'),
('Fantasía'),
('Ciencia ficción'),
('Terror'),
('Infantil'),
('Misterio'),
('Histórico'),
('Mitología'),
('Humor'),
('Autoayuda'),
('Poesía');

INSERT INTO audiolibros (titulo, autor, descripcion, img) VALUES
('Harry Potter y la piedra filosofal', 2, '«Con las manos temblorosas, Harry le dio la vuelta al sobre y vio un sello de lacre púrpura con un escudo de armas: un león, un águila, un tejón y una serpiente, que rodeaban una gran letra H.»
Harry Potter nunca ha oído hablar de Hogwarts hasta que empiezan a caer cartas en el felpudo del número 4 de Privet Drive. Llevan la dirección escrita con tinta verde en un sobre de pergamino amarillento con un sello de lacre púrpura, y sus horripilantes tíos se apresuran a confiscarlas. Más tarde, el día que Harry cumple once años, Rubeus Hagrid, un hombre gigantesco cuyos ojos brillan como escarabajos negros, irrumpe con una noticia extraordinaria: Harry Potter es un mago, y le han concedido una plaza en el Colegio Hogwarts de Magia y Hechicería. ¡Está a punto de comenzar una aventura increíble!', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HarryPotter1.jpeg'),
('La Odisea', 3, 'Este poema épico, compuesto por veinticuatro cantos, narra la vuelta a casa, tras una década de guerra, del héroe griego Odiseo (Ulises, en latín). Para el regreso a Itaca, su hogar y su reino, y tras una ofensa al dios Poseidón, Odiseo dedica otros diez años, condenado a navegar sin rumbo sufriendo diversas vicisitudes.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaOdisea.png'),
('Orgullo y Prejuicio', 4, '«Es una verdad universalmente aceptada que todo soltero en posesión de una gran fortuna necesita una esposa ». Nueva traducción ilustrada de la novela de Jane Austen. Este comienzo, que, junto con el de Ana Karénina, es quizás uno de los más famosos de la historia de la literatura, nos introduce sabiamente en el mundo de Jane Austen y de su novela más emblemática. Orgullo y prejuicio, publicada en 1813 tras el éxito de Juicio y sentimiento, reúne de forma ejemplar sus temas recurrentes y su visión inimitable en la historia de las cinco hijas de la señora Bennett, que no tiene otro objetivo en su vida que conseguir una buena boda para todas ellas. Dos ricos jóvenes, el señor Bingley y el señor Darcy, aparecen en su punto de mira e inmediatamente se ven señalados como posibles  presas . De hecho, la relación entre la hija mayor, Jane, y el señor Bingley parece muy prometedora pero, por influencia del arrogante señor Darcy, se frustran todas las esperanzas. La intervención de Elizabeth, la hija segunda, perspicaz, consciente de su valor, y algo rebelde, determinará el rumbo de la novela. En ella el opresivo ambiente de la familia, la presión del matrimonio, la diferencia de clases, el fantasma de la pobreza y la delicada sensibilidad de una heroína decidida, pero no libre de errores de juicio y dudas de comportamiento, se conjugan para crear una obra maestra leída a lo largo de más de dos siglos.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/OrgulloYPrejuicio.jpg'),
('El Coco', 5, 'La estudiante de secundaria Sadie Harper (Sophie Tatcher) y su hermana menor Sawyer (Vivien Lyra Blair) se están recuperando de la reciente muerte de su madre y no reciben mucho apoyo de su padre, Will (Chris Messina), un terapeuta que está lidiando con su propio dolor.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElCoco.jpg'),
('El Hombre Del Traje Negro', 5, 'A los 90 años y antes de que le llegue la muerte, Gary decide poner por escrito lo que le sucedió en 1914, cuando sólo tenía 9, para que quede constancia. Un encuentro paranormal con un hombre con un traje negro de tres piezas mientras pescaba truchas en la orilla de un solitario río.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElHombreDelTrajeNegro.jpg'),
('Popsy', 5, 'Sheridan es un adicto al juego quien ha contraído una enorme deuda. Para pagarla, secuestra a niños a petición de un mafioso. El niño que secuestra resulta ser un vampiro al igual que su Abuelito (Popsy en inglés) que no esta dispuesto a dejar que Sheridan huya con su nieto.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Popsy.jpg'),
('Un Trago De Despedida', 5, 'Cierta noche de invierno, en un bar, varios parroquianos mantienen sus charlas habituales. Cuando están a punto de cerrar, un hombre muy alarmado entra pidiendo ayuda: su coche ha quedado atrapado por la nieve en la carretera que conduce a Jerusalem’s Lot (o Salem’s lot), un pueblo «aparentemente» abandonado.
Lo que sobrecoge a esos parroquianos es que la mujer y la hija del conductor han quedado en el interior del vehículo. Inmediatamente se ponen en marcha, aunque quizá cuando lleguen sea tarde.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElUmbralDeLaNoche.jpg'),
('Asesinato en el campo de golf', 5, 'Hércules Poirot recibe una carta de Paul Renauld, quien le dice que teme por su vida y le urge a que acuda en su ayuda. Así, junto con su amigo el capitán Hastings, el detective se dirige rápido al norte de Francia para prestar sus servicios al nuevo cliente. Sin embargo, llegan demasiado tarde: el cuerpo de Renauld yace apuñalado en medio de un campo de golf.
Mientras Poirot investiga la escena del crimen y a los posibles sospechosos, descubre otro cuerpo asesinado de la misma manera que el primero, y con la misma arma. ¿Qué tienen en común estos hombres? ¿Quién los ha matado? ¿Y por qué Poirot no deja de pensar en un crimen cometido años atrás?', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/AsesinatoEnElCampoDeGolf.jpg'),
('Muerte en el Nilo', 6, 'Un célebre caso que pone a prueba la extrema lucidez de Hércules Poirot.
Durante unas placenteras vacaciones en Egipto, el detective Hércules Poirot coincide con Linnet y Simon, unos conocidos suyos que están de luna de miel en el país de los faraones.
El encanto de tan maravillosos días se rompe cuando una mañana, en el transcurso de un crucero por el Nilo, la bella Linnet aparece muerta de un disparo en la cabeza.
¿Será capaz Poirot de encontrar al asesino de la joven esposa? ¿Será capaz de discernir entre imaginación y realidad, aun estando a bordo la ex pareja de Simon, empeñada desde el mismo día de la boda en arruinar su matrimonio con la desafortunada Linnet?
El misterio está servido.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/MuerteEnElNilo.jpg'),
('El misterio del tren azul', 6, 'El Tren Azul con destino a Niza transporta una valiosa carga: el mayor rubí del mundo, el "Corazón de Fuego", un regalo de un magnate americano del petróleo para su querida hija, Ruth Kettering. Pero al llegar a la Costa Azul, se descubre que la propietaria de la joya ha sido brutalmente asesinada y que el rubí ha desaparecido. El millonario Rufus Van Aldin, muy afectado por la muerte de su heredera, contrata al detective Hercule Poirot para que resuelva el estremecedor suceso. El caso irá adquiriendo una creciente complejidad a medida que Poirot descubra el turbulento pasado de la víctima: su recientemente frustrado matrimonio, la tensa relación que mantenía con su padre y la existencia de un ex pretendiente con quien debía encontrarse en Niza. Es un caso aparentemente imposible de resolver, donde todos son sospechosos y ningún indicio conduce al culpable. Una historia de intriga apasionante donde nada es lo que parece que mantendrá al lector sin aliento hasta la última página. "Hercule Poirot no es un toxicómano atormentado, como Sherlock Holmes, o un glotón desencantado, como Pepe Carvalho, o un alcohólico cínico, como Philip Marlowe. Es un sibarita que vive como un pachá e idolatra el clasismo británico." Del Prólogo de Enric González', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElMisterioDelTrenAzul.jpg'),
('Un dios solitario y otros relatos', 6, 'Como muchos de sus contemporáneos, Agatha Christie escribió relatos para diversas revistas en los años veinte y treinta, y casi todos ellos acabaron incluidos más tarde en libros recopilatorios. Este libro, casi una pieza de coleccionista, muestra a la maestra del crimen en su etapa de formación, y sus lectores podrán comprobar una vez más su gran dominio de la caracterización y su habilidad para los desenlaces imprevistos', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/UnDiosSolitarioYOtrosRelatos.jpg'),
('Miss Marple y 13 problemas', 6, '"¿Qué le parece si formásemos un club? Lo llamaremos el Club de los Martes. Nos reuniremos y cada uno deberá exponer un problema real y los demás competiremos para solucionarlo". A partir de esta conversación nacen trece magníficas historias policíacas.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/MissMarpleY13Problemas.jpg'),
('Un escándalo en Bohemia', 7, 'Escándalo en Bohemia es el primero de los 56 relatos cortos sobre Sherlock Holmes escrito por Arthur Conan Doyle y la primera historia de Sherlock Holmes ilustrada por Sidney Paget. Fue publicado originalmente en The Strand Magazine y posteriormente recogido en la colección Las aventuras de Sherlock Holmes. Sherlock Holmes es llamado por un caballero enmascarado. Se presenta como el conde Von Kramm, un agente de un cliente adinerado, pero Holmes deduce rápidamente que se trata de Wilhelm Gottsreich Sigismond von Ormstein, gran duque de Cassel-Felstein y rey hereditario de Bohemia. El rey, arrancándose la máscara, lo admite.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/UnEscandaloEnBohemia.jpg'),
('El aristócrata solterón', 7, 'El Aristócrata Solterón relata el caso de la extraña desaparición de la rica heredera Hatty Doran. Hija única del multimillonario Aloysius Doran, se ha esfumado tras su matrimonio con el citado Lord St. Simon, segundo hijo del duque de Balmoral y perteneciente a la más rancia aristocracia de Inglaterra. A pesar de la poca simpatía que inspira a Holmes el estirado personaje, el caso le interesa, y se hace cargo de él.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElAristocrataSolteron.png'),
('El misterio de Cooper Beeches', 7, 'Violet Hunter acude a la consulta de Holmes después de que le ofrezcan un puesto de institutriz sujeto a raras condiciones, incluyendo una que la obliga a cortarse el pelo. El sueldo es extremadamente elevado, de 120 libras, y, por ende, decide aceptarlo, aunque Holmes le aconseja que le llame si lo necesita. Tras varios sucesos extraños, incluido el descubrimiento de una zona sellada de la casa, se decide a llamarle. Holmes descubre que habían mantenido a alguien preso en esa parte de la propiedad, pero, cuando entra acompañado de Watson y la propia Hunter, se topa con que está vacía. Los acusan de liberar a la prisionera, que era la hija de la empleador de Hunter, y este manda al perro a perseguirlos; sin embargo, el animal lo ataca a él. Se descubre que a Hunter la habían contratado para hacerse pasar por la hija de su empleador, de modo que su prometido se creyera que ella ya no estaba interesada en verla; la hija, no obstante, se había escapado y conseguido casarse.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElMisterioDeCooperBeeches.jpg'),
('Caperucita Roja', 8, 'Caperucita Roja es una niña que quería mucho a su abuela; un día su madre le da una cesta con comida para que se la lleve a la abuela, que está enferma y vive en una casa algo lejos de ellas. ​ En el camino se encuentra con el Lobo Feroz que la reta a una carrera hasta la casa de la abuela.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/CaperucitaRoja.jpg'),
('La ratita presumida', 8, 'La RATITA se quejaba de una vida aburrida y llena de monotonía. No se esperaba que un lazo revolucionaría tanto su día de la forma en que lo hizo. A partir de ahí, un séquito de pretendientes intentaran seducirla para poder casarse con ella.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaRatitaPresumida.jpg'),
('Los siete cabritillos y el lobo', 8, 'Mamá cabra y sus siete cabritillos vivían en una pequeña casa en el bosque. Un día, mamá cabra, llamó a sus pequeños y les dijo: »Voy a recolectar bayas. No abráis la puerta a nadie, a nadie os digo. Y recordad que el lobo se disfraza: pero si estáis atentos, lo reconoceréis por la voz y por las patas negras».', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LosSieteCabritillosYElLobo.jpg'),
('El gato con botas', 8, 'Había una vez un molinero que dejó en herencia a sus hijos un molino, un asno y un gato. Al pequeño le tocó el gato, que era muy listo. El gato le dijo a su nuevo dueño que si le daba unas botas y un saco, no se arrepentiría. ¿Qué es lo que tramaba el felino?
Había una vez un molinero que dejó en herencia a sus hijos un molino, un asno y un gato. Al pequeño le tocó el gato, que era muy listo. El gato le dijo a su nuevo dueño que si le daba unas botas y un saco, no se arrepentiría. ¿Qué es lo que tramaba el felino?', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElGatoConBotas.jpg'),
('Las hadas', 8, 'Este cuento trata de una mujer viuda con dos hijas. La madre prefería a su hija mayor y a la menor la detestaba, encargandole trabajos domésticos muy pesados. Un día, la hija menor fue a un arroyo donde un hada le regala un don maravilloso de convertir las palabras en flores y piedras preciosas.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LasHadas.jpg'),
('Hansel y Gretel', 9, 'Dos hermanos, una niña llamada Gretel y un niño llamado Hansel, hijos de un leñador, viven con su padre y su madrastra cerca de un bosque, la madrastra odiaba a los niños. Como eran muy pobres, a la madrastra se le ocurrió la idea de llevar a los niños a la parte más profunda del bosque y dejarlos allí abandonados.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HanselYGretel.jpg'),
('El piojito y la pulguita', 9, 'Un piojito y una pulguita hacían vida en común y cocían su cerveza en una cáscara de huevo. He aquí que el piojito se cayó dentro y se quemó. Ante aquella desgracia, la pulguita se puso a llorar a voz en grito. Al oírla, preguntó la puerta de la habitación: “¿Por qué lloras, Pulguita?” – “Porque Piojito se ha quemado. Y la noticia irá corriendo de boca en boca, se enterarán la escobita, el fogoncito, el arbolillo, la muchachita y la fuentecita.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElPiojitoYLaPulguita.png'),
('El gigante egoísta', 10, 'Los niños del pueblo juegan en el amplio jardin de la casa de un Gigante. Harto de sus voces y de sus risas, el Gigante, un ser solitario y egoista, levanta un muro tan alto que los pequeños no pueden saltarlo. Desde ese momento ya no regresa a su jardin la primavera.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElGiganteEgoista.jpg'),
('El soldadito de plomo', 11, 'En la narración de Hans Christian Andersen, el soldado de una sola pierna se enamora de la bailarina de palacio, es arrancado de su pequeño mundo, comienza un viaje aventurero en un barco de papel y, finalmente, regresa a casa, donde se le depara un final agridulce.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElSoldaditoDePlomo.jpg'),
('La princesa y el guisante', 11, 'La protagonista, Amira, hija del rey Mustafá de Arabia, decide huir para evitar que su padre la case con un sultán que ella no conoce. Lo mismo le pasa al príncipe Arnaldo cuando su madre le obliga a casarse con la joven que sea capaz de notar la presencia de un guisante escondido bajo siete colchones.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaPrincesaYElGuisante.jpg'),
('La vendedora de fósforos', 11, 'La vendedora de fósforos de Andersen, el burro de Bresson, la relación entre un guerrillero alemán y una pianista argentina, y Helmut Lachenmann tratando de montar una ópera con la orquesta del Teatro Colón en huelga. Marie y Walter intentarán con su hija vivir en el medio de todo eso.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaVendedoraDeFosforos.jpg'),
('El último sueño del viejo roble', 11, 'Trata la historia de un viejo roble que vive junto a un puerto pesquero. Tiene 365 años y a su alrededor, cada verano, revolotean las moscas que solo viven un día. Llega el otoño y las hojas comienzan a caer y el árbol y los animales se preparan para los largos meses de invierno.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElUltimoSueñoDelViejoRoble.png'),
('Los tres cerditos y el lobo', 1, 'Los tres cerditos y el lobo
Cada uno de los tres cerditos tiene una personalidad distinta. El encuentro de cada uno de ellos con el lobo la sacará a relucir.
El lobo de los tres cerditos
A lo mejor, el lobo de los tres cerditos no era tan malo. Cuenta esta historia que cuando eran pequeños los tres cerditos y el lobo se encontraron en una playa y algo ocurrió...', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LosTresCerditosYElLobo.jpg'),
('El hombre del saco', 1, 'Con trece años, es víctima de un violento depredador sexual infantil que le destroza una vida de sueños e intenta matarla. Tras una vida al margen de la ley, ingresa en prisión acusada de perpetrar una serie de atracos a entidades bancarias, en la que pasara ocho años de su vida.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElHombreDelSaco.jpg'),
('Las tres naranjitas', 1, 'Un príncipe sale de palacio en busca de esposa. Un anciano le indica que ruta seguir y cómo enfrentar los peligros del camino. Tras fracasar en dos oportunidades, a la tercera encuentra su princesa, aunque aún ha pasar otras peripecias antes de su boda.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LasTresNaranjitas.jpg'),
('Los ladrones arrepentidos', 1, 'Cuentos y Leyendas Populares', 'https://narrativesarchivos.blob.core.windows.net/imagenes/LosLadronesArrepentidos.jpg'),
('El Arte de la Paz', 12, 'Las enseñanzas recopiladas en este libro proceden de las charlas y escritos de Morihei Ueshiba, fundador del popular arte marcial japonés conocido como aikido, una disciplina psicofísica que él denominó "arte de la paz", y que ofrece un camino no violento hacia la victoria frente al conflicto.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElArteDeLaPaz.jpg'),
('Las 9 Revelaciones', 13, 'La gran aventura espiritual que conquistó a millones de lectores en todo el mundo.
Revelaciones clave para que podamos comprender el presente y enfrentarnos al futuro.
Al principio solo era un pequeño volumen que su autor, James Redfield,  publicó por su cuenta y riesgo. Pero muy pronto todos estaban hablando de Las nueve revelaciones como del libro que cambiaría nuestra visión acerca del destino humano. Una decada más tarde, lleva vendidos casi seis millones de ejemplares en treinta y dos países.
La historia que Redfield nos cuenta habla de un antiguo manuscrito  escondido en la selva peruana, que guarda en sus páginas nueve  revelaciones esenciales para comprender el presente y enfrentarse al futuro. La búsqueda del texto perdido supone un gran esfuerzo no  exento de riesgos, pero la tenacidad de un pequeño grupo de sabios  aventureros pondrá por fin en manos de todos estas claves de un mensaje  simple y directo que apunta a nuestra espiritualidad y puede abrir un nuevo capítulo en nuestras vidas.
Una apasionante historia de aventura y descubrimiento, una guía con el  poder de cristalizar tus percepciones y dirigir tus pasos con una nueva energía y optimismo.
Un libro que aparece solo una vez en la vida.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LasNueveRevelaciones.jpg'),
('Tus pensamientos crean tu vida', 14, 'Nuestras ideas y creencias pueden producir enfermedad, insatisfacción y falta de armonía. La clave para convertir las creencias negativas en positivas está en aprender a amarnos a nosotros mismos. Esta nueva actitud unida a nuestra disposición a cambiar creará la vida que de veras deseamos. 
"Los pensamientos que tenemos y las palabras que decimos son tremendamente poderosos. Es casi como si al tener un pensamiento o pronunciar una palabra, éstos salieran de nosotros para regresar convertidos en experiencias."', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/TusPensamientosCreanTuVida.jpg'),
('Tú puedes sanar tu vida', 14, 'El gran clásico de Louis L. Hay, un bestseller que inició el movimiento de crecimiento personal en todo el mundo y que hoy día se sigue editando en más de treinta países. El planteamiento del libro es muy sencillo: todos tenemos el poder de transformar nuestra vida porque los pensamientos conforman la realidad de cada cual. A partir de esta idea, la autora propone un metodo de autotransformación que enseña no sólo a crear paz y armonía tanto interior como exterior sino a descubrir el significado de la autentica autoestima. Usted puede sanar su vida no ha perdido vigencia con el paso de los años; al contrario, las más modernas teorías científicas corroboran sus planteamientos. Muchos autores han recuperado las ideas de Hay con posterioridad pero ninguno ha sabido exponerlos con tanta sencillez y acierto. Hoy, Ediciones Urano vuelve pone al alcance de los lectores la nueva edición de un clásico para leer y releer.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/TuPuedesSanarTuVida.jpg'),
('La ciencia de hacerse rico', 15, 'Existe una ciencia para hacerse rico, y es una ciencia exacta, como lo son el álgebra o las matemáticas. Hay ciertas leyes que gobiernan el proceso de adquirir la riqueza: leyes que, una vez aprendidas y seguidas por cualquier persona, harán que se enriquezca con una certeza matemática. El presente libro, sin duda el manual para enriquecerse mas famoso de todo los tiempo, le revelara como alcanzar la riqueza y la prosperidad mediante el sistema que usaron cientos de multimillonarios norteamericanos.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaCienciaDeHacerseRico.jpg'),
('El poder del ahora', 16, 'Con más de cinco millones de ejemplares vendidos, EL PODER DEL AHORA, un fenómeno que se ha ido extendiendo de boca a boca desde que se publicó por primera vez, es uno de esos libros extraordinarios capaces de crear una experiencia tal en los lectores que pueden cambiar radicalmente sus vidas para mejor.
Para adentrarse en EL PODER DEL AHORA tendremos que dejar atrás nuestra mente analítica y su falso yo, el ego. Desde la primera página de este extraordinario libro nos elevamos a una mayor altura y respiramos un aire más ligero. Conectamos con la esencia indestructible de nuestro Ser: "la Vida Una omnipresente, eterna, que está más allá de la miríada de formas de vida sujetas al nacimiento y a la muerte". Aunque el viaje es todo un reto, Eckhart Tolle nos guía usando un lenguaje simple y un sencillo formato de pregunta-respuesta.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElPoderDelAhora.jpg'),
('Una nueva tierra', 16, 'Si ya se ha iniciado en usted el proceso del despertar, éste se acelerará y se intensificará con esta lecturaLa finalidad principal de este libro no es darle a su mente más información ni creencias, ni tratar de convencerlo de algo, sino generar en usted un cambio de conciencia, es decir, un despertar. En ese sentido, este libro no es #interesante#, puesto que esa palabra implica la posibilidad de mantener una distancia, jugar con las ideas y los conceptos en la mente y manifestarse de acuerdo o en desacuerdo con ellos. Este libro es sobre usted. Si no contribuye a modificar el estado de su conciencia, no tendrá significado alguno. Solamente servirá para despertar a quienes estén listos. Aunque no todo el mundo está listo, muchas personas sí lo están y cada vez que alguien despierta se amplifica el ímpetu de la conciencia colectiva, facilitando el cambio para los demás. Si no sabe lo que significa despertar, siga leyendo. Es solamente a través del despertar que podrá comprender el verdadero significado de la palabra. Basta con un destello para iniciar el proceso, que es irreversible. Para algunos, este libro será ese destello; para muchos otros que quizás no se hayan dado cuenta, el proceso ya ha comenzado. Este libro les ayudará a reconocerlo. Algunos habrán emprendido el camino como consecuencia del sufrimiento o de una pérdida, mientras que otros quizás lo hayan hecho a través del contacto con un maestro o una enseñanza espiritual, la lectura de El poder del ahora o de algún otro libro pleno de vida espiritual y de energía transformadora, o una combinación de lo anterior. Si ya se ha iniciado en usted el proceso del despertar, éste se acelerará y se intensificará con esta lectura.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/UnaNuevaTierra.jpg'),
('101 Formas de Transformar su Vida', 17, 'Aunque el ser humano fue creado con un propósito, debemos reconocer que nos perdimos. Estamos viviendo una vida con dificultades, la oscuridad a la que DIOS no le gusto; esa oscuridad se ha apoderado de la conciencia para impedir que veamos el camino de regreso.
Cuando observamos una catástrofe; como las que ocurren, cada día con más frecuencia, hasta sentimos un poco de temor, algunos dicen por ejemplo: la tierra se puede salvar si todos sembramos un árbol, pero en el fondo sabemos que no es así, el problema es grave, el ser humano debe cambiar para que este planeta se salve.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/101FormasDeTransdormarSuVida.jpg'),
('Al sueño', 18, 'Poema de Francisco de Quevedo', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasQuevedo.jpg'),
('Epístola satírica y censoria', 18, 'Poema de Francisco de Quevedo', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasQuevedo.jpg'),
('Memoria inmortal de don Pedro Girón', 18, 'Poema de Francisco de Quevedo', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasQuevedo.jpg'),
('Conoce la diligencia con que se acerca la muerte', 18, 'Poema de Francisco de Quevedo', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasQuevedo.jpg'),
('Enseña cómo todas las cosas avisan la muerte', 18, 'Poema de Francisco de Quevedo', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasQuevedo.jpg'),
('Letrilla Satírica «Poderoso Caballero es don Dinero»', 18, 'Poema de Francisco de Quevedo', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasQuevedo.jpg'),
('Romance de Angélica y Medoro', 19, 'Poema de Luis de Góngora', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasGongora.jpg'),
('Romance «Servía en Orán al Rey»', 19, 'Poema de Luis de Góngora', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasGongora.jpg'),
('Romance «Entre los sueltos caballos»', 19, 'Poema de Luis de Góngora', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasGongora.jpg'),
('Letrilla «Ande yo caliente, y ríase la gente»', 19, 'Poema de Luis de Góngora', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasGongora.jpg'),
('Letrilla «Dejadme llorar, orillas del mar»', 19, 'Poema de Luis de Góngora', 'https://narrativesarchivos.blob.core.windows.net/imagenes/PoemasGongora.jpg'),
('El príncipe cuervo', 20, 'Edward de Raaf, conde de Swartingham, necesita con urgencia un secretario que ponga orden en sus caóticas finanzas. El problema es que, con su carácter, espanta a todos los candidatos. Para Anna Wren el puesto es la solución a sus problemas, después de enviudar de un marido infiel y quedarse en la ruina. La atracción entre ambos personajes queda patente desde el primer momento, aunque Edward no parece muy dispuesto a dejarse llevar por ella. Cuando Anna descubre que el conde es habitual de un conocido burdel de Londres, decide poner en marcha una pequeña mascarada. Porque en el juego de la seducción, no existen reglas?', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElPrincipeCuervo.jpg'),
('El príncipe leopardo', 20, 'Lo único que jamás debe hacer una dama... 
La adinerada lady Georgina Maitland no quiere un esposo, aunque no le vendría nada mal un administrador que gestione sus propiedades. Es ponerle la vista encima a Harry Pye, y Georgina sabe que no sólo está tratando con un sirviente, sino con un hombre.
...es enamorarse... 
Harry ha conocido a muchos aristócratas... incluyendo a uno en particular que es su enemigo jurado. Pero Harry jamás ha conocido a una hermosa dama tan independiente, desinhibida y ansiosa por estar en sus brazos. 
...de su sirviente.
Con todo, es imposible mantener una aventura discreta cuando el envenenamiento de ovejas, asesinato de aldeanos y un magistrado rabioso tiene alborotado al condado entero. Los lugareños culpan a Harry de todo. Georgiana no tardará en hacer algo para poder mantenerse a flote ella misma y salvar a Harry de la horca... sin perderse otra noche de amor.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElPrincipeLeopardo.jpg'),
('El príncipe serpiente', 20, 'Cuando el demonio conoce a un ángel... 
Lucy Craddock-Hayes está contenta con su tranquila vida campestre. Hasta el día en que tropieza con un hombre inconsciente —un hombre «desnudo» inconsciente— y pierde para siempre su inocencia. 
...puede llevarla hasta el séptimo cielo... 
El vizconde Simon Iddesleigh ha recibido una brutal paliza por parte de sus enemigos que a punto ha estado de acabar con su vida. Ahora Simon solamente piensa en vengarse. Pero cuando Lucy le cuida y le devuelve la salud, su honestidad espanta sus hastiadas sensibilidades... aun cuando despierta un deseo que amenaza con consumirlos a ambos. 
...o al infierno. 
Embrujada por la astuta inteligencia de Simon, sus modales mundanos e inclusos sus zapatos de tacón rojo, Lucy se enamora rápida y profundamente de él. Pero aunque el honor le impida seducirla, su venganza guiará a sus atacantes hasta su puerta. Mientras Simon hace la guerra a sus enemigos, Lucy libra una guerra propia por su alma empleando la única arma que tiene a su alcance... su amor...', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElPrincipeSerpiente.jpg'),
('La princesa de hielo', 20, 'SIETE NOCHES DE PECADO
Como la madam de la Gruta de Afrodita, el burdel más famoso de Londres, Coral Smythe sabe todo lo posible acerca de las necesidades y los deseos de los hombres. Sin embargo, ella nunca ha experimentado el amor de uno solo, ni siquiera lel del capitán Isaac Wargate cuyos ojos de halcón la miran fijamente con condena ... y lujuria.
SIETE NOCHES DE ÉXTASIS
El corazón del capitán Wargate desaprueba a la sensual madam que siempre lleva una máscara de oro. Ella distrae a sus oficiales de los buques y de su deber, como tambien a él. Pero cuando la misma Coral es ofrecida como premio en un juego de azar, Wargate impulsivamente entra ... y gana.
SIETE NOCHES DE AMOR
Ahora, el puritano capitán de la Armada contará de siete noches para aprender todo lo que pueda acerca de la misteriosa señora, y lo que sabe de los deseos de un hombre. Pero cuando Coral es amenazada por el nuevo dueño de la Gruta de Afrodita, ¿estárá Wargate dispuesto a tener una oportunidad con la mujer debajo de la máscara ... y el amor?', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaPrincesaDeHielo.jpg'),
('Encajes y pecados', 21, 'La luz de gas iluminaba los cabellos dorados de Alana van Alen. Nacida para el lujo, se codeaba con los Astor y los Vanderbilt en los grandes salones. Sin embargo, se estremeció de miedo y algo más cuando se encontró ante el apuesto e implacable Trevor Sheridan. Sheridan, el hombre que había llevado a la bancarrota a la familia de ella y pretendía sacar a la luz el escandaloso secreto familiar en caso de que Alana no aceptara su ultrajante proposicion, su chantaje emocional... ni el beso que le paralizó el corazón.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/EncajesYPecados.jpg'),
('Fugitiva', 21, 'Cuando la bella aristócrata Christabel Van Alen es acusada falsamente de asesinato, escapa de su vida en Nueva York hacia el salvaje Oeste con la intención de crearse una nueva identidad. Sin embargo, sus planes se verán frustrados cuando se interpone en su camino Cain, un duro e implacable representante de la ley que la perseguirá sin tregua allá donde vaya. 
El marshal captura a la joven con intenciones de llevarla ante la justicia, pero el deseo y la violenta pasión que surge entre ellos harán que todo en lo que ha creído Cain hasta el momento se derrumbe y deba escoger entre la ley… o la mujer a la que ama y sin la que ya no puede vivir.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Fugitiva.jpg'),
('Indómito', 22, 'El peligroso y enigmático Dominic le Sabre regresa a Inglaterra colmado de gloria y riquezas obtenidas en las Cruzadas, para reclamar su recompensa: la hermosa dama sajona que le ha sido destinada por el rey. 
Sin embargo, lady Margaret de Blackthorne, atrapada en una red de odio, no puede ceder ante el invasor normando. Pero lo que no imagina es que va a ser sometida sin piedad a una implacable seducción por parte del fiero guerrero, en la que ambos perderán su corazón y… también su alma. 
Juntos deberán enfrentarse a las traiciones que les rodean y librar la batalla más importante de sus vidas. Una batalla en la que tendrán que luchar por la violenta pasión que les une, y… por su amor.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Indomito.jpg'),
('Prohibido', 22, 'Una antigua profecía… 
Amber es la única descendiente de una antigua tribu celta y está destinada a llevar una vida solitaria dedicada a la sanación hasta que, según predijeron a su nacimiento, un hombre la conduzca hasta la luz… o la oscuridad. 
Un pasión prohibida… 
Duncan es uno de los guerreros más poderosos de Inglaterra, un hombre duro y peligroso hecho a sí mismo, pero ahora ha perdido la memoria y ha caído en manos de sus enemigos. Lo que nunca hubiera podido imaginar es que hallaría la pasión, el amor y la ternura en una mujer que le está… prohi-bida.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Prohibido.jpg'),
('Hechicera', 22, 'Simon le Sabre ha jurado no amar jamás, y aunque acepta desposar a una bella heredera normanda para lograr la paz en sus tierras, el matrimonio no es para él más que una simple obligación. Sin embargo, el poderoso guerrero que nunca ha conocido la derrota, caerá rendido ante su esposa y su único objetivo será conquistarla y seducirla. Ariane Deguerre, una inocente y dulce hechicera, se ha visto obligada a enfrentarse toda su vida a la frialdad y la crueldad, por lo que llega a Simon reticente... y aterrorizada. Lo último que la joven esperaba era sentirse cautivada por el hombre que el destino ha cruzado en su camino, un hombre que hace surgir en ella un fiero deseo más fuerte que el odio y la traición. Ambos deberán aprender que la paz que tanto ansían sólo podrá lograrse mediante la violenta pasión y el profundo amor que llegará a unirlos.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Hechicera.jpg'),
('Harry Potter y la cámara secreta', 2, '«Hay una conspiración, Harry Potter. Una conspiración para hacer que este año sucedan las cosas más terribles en el Colegio Hogwarts de Magia y Hechicería.»
El verano de Harry Potter ha incluido el peor cumpleaños de su vida, las funestas advertencias de un elfo doméstico llamado Dobby y el rescate de casa de los Dursley protagonizado por su amigo Ron Weasley al volante de un coche mágico volador. De vuelta en el Colegio Hogwarts de Magia y Hechicería, donde va a empezar su segundo curso, Harry oye unos extraños susurros que resuenan por los pasillos vacíos. Y entonces empiezan los ataques y varios alumnos aparecen petrificados... Por lo visto, las siniestras predicciones de Dobby se están cumpliendo....', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HarryPotter2.jpg'),
('Harry Potter y el prisionero de Azkaban', 2, '«Bienvenido al autobús noctámbulo, transporte de emergencia para el  brujo abandonado a su suerte. Levante la varita, suba a bordo y lo llevaremos a donde quiera.»
Cuando el autobús noctámbulo irrumpe en una calle oscura y frena con  fuertes chirridos delante de Harry, comienza para él un nuevo curso en  Hogwarts, lleno de acontecimientos extraordinarios. Sirius Black,  asesino y seguidor de lord Voldemort, se ha fugado, y dicen que va en  busca de Harry. En su primera clase de Adivinación, la profesora  Trelawney ve un augurio de muerte en las hojas de té de la taza de  Harry... Pero quizá lo más aterrador sean los dementores que patrullan  por los jardines del colegio, capaces de sorberte el alma con su beso...', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HarryPotter3.jpg'),
('Harry Potter y el cáliz de fuego', 2, '"Habrá tres pruebas, espaciadas en el curso escolar, que medirán a los  campeones en muchos aspectos diferentes: sus habilidades mágicas, su  osadía, sus dotes de deducción y, por supuesto, su capacidad para sortear el peligro."
Se va a celebrar en Hogwarts el Torneo de los Tres Magos. Sólo los  alumnos mayores de diecisiete años pueden participar en esta competición, pero, aun así, Harry sueña con ganarla. En Halloween,  cuando el cáliz de fuego elige a los campeones, Harry se lleva una  sorpresa al ver que su nombre es uno de los escogidos por el cáliz  mágico. Durante el torneo deberá enfrentarse a desafíos mortales,  dragones y magos tenebrosos, pero con la ayuda de Ron y Hermione, sus mejores amigos, ¡quizá logre salir con vida!', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HarryPotter4.jpg'),
('Mentes poderosas', 23, 'Una misteriosa enfermedad ha acabado con las vidas de la mayoría de los  niños del país. Ruby ha sobrevivido, pero ella y muchos más deberán  enfrentarse a algo mucho peor que un virus: unas terroríficas habilidades que no son capaces de controlar.
Ruby es enviada a Thurmond, un brutal campo de rehabilitación, donde  aprende a temer y a reprimir su nuevo poder. Pero ¿y si aprender a  controlarlo es la única posibilidad de supervivencia de toda una generación?
Ahora, despues de pasar seis años encerrada, Ruby se ha convertido en  uno de los elementos más peligrosos... y finalmente, con dieciseis años, ha logrado huir.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/MentesPoderosas.jpg'),
('Nunca olvidan', 23, 'Ruby no pidió las habilidades que casi le cuestan la vida. Ahora debe recurrir a ellas para hundir un gobierno corrupto en un mundo donde los niños han sido eliminados.
Cuando le confían un secreto explosivo, Ruby se lanza a un peligroso viaje para encontrar a Liam Stewart, el chico que lleva consigo la verdad sobre la enfermedad que sumió el mundo en el caos. El chico del que se enamoró y al que esperaba no ver nunca más.
Un viaje a traves de un país desesperado en busca de respuestas... ¿y si ganar la batalla supone perderse a sí misma?', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/NuncaOlvidan.jpg'),
('Una luz incierta', 23, 'El tiempo se agota. Mientras miles de chicos languidecen encerrados en los campos, Ruby y el grupo que sobrevivió a los últimos ataques se reagrupan en el note para retomar su objetivo inicial: liberar a los demás. Solo cuentan con un arma y es de doble filo: la prueba de la conspiración del gobierno para encubrir el origen de la misteriosa plaga que acabó con la vida de tanto jóvenes y que convirtió a los pocios supervivientes en unos seres extraños y temidos. Ahora, un nuevo riesgo se suma a la persecucción mortal que sufren Ruby y los demás por parte del gobierno: las tensiones aumentan en el seno del grupo cuando empiezan a correr rumores sobre una posible cura. Con el destino de toda una generación en sus manos, Ruby sabe que todo pende de un hilo... Cualquier paso en falso podría ser la chispa que destara el caos. LLEGA EL EXPLOSIVO FINAL DE UNA SAGA TREPIDANTE LA LUZ VOLVERÇ A BRILLAR... O SE APAGARÇ PARA SIEMPRE', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/UnaLuzIncierta.jpg'),
('Las crónicas de Narnia. El sobrino del mago', 24, 'Dos amigos, víctimas del poder de unos anillos mágicos, son arrojados a otro mundo en el que una malvada hechicera intenta convertirlos en sus esclavos. Pero entonces aparece Aslan y crea Narnia, un mundo poblado por seres mitológicos, animales parlantes y brujas malvadas.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Narnia1.jpg'),
('Las crónicas de Narnia. El león, la bruja y el armario', 24, 'Narnia, la tierra donde todo puede suceder
Cuatro niños que viven en una casa solitaria descubren un armario que da acceso a Narnia, un país congelado en un invierno eterno y sin Navidad. Cumpliendo con las viejas profecías, los niños–junto con el león Aslan- liberarán al país de la tiranía de la Bruja Blanca.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Narnia2.jpg');

INSERT INTO genero_audiolibro (audiolibro, genero) VALUES
(3, 1),
(51, 1),
(52, 1),
(53, 1),
(54, 1),
(55, 1),
(56, 1),
(57, 1),
(58, 1),
(59, 1),
(1, 3),
(60, 3),
(61, 3),
(62, 3),
(63, 3),
(64, 3),
(65, 3),
(66, 3),
(67, 3),
(4, 5),
(5, 5),
(6, 5),
(7, 5),
(16, 6),
(17, 6),
(18, 6),
(19, 6),
(20, 6),
(21, 6),
(22, 6),
(23, 6),
(24, 6),
(25, 6),
(26, 6),
(27, 6),
(28, 6),
(29, 6),
(30, 6),
(31, 6),
(8, 7),
(9, 7),
(10, 7),
(11, 7),
(12, 7),
(13, 7),
(14, 7),
(15, 7),
(2, 8),
(32, 11),
(33, 11),
(34, 11),
(35, 11),
(36, 11),
(37, 11),
(38, 11),
(39, 11),
(40, 12),
(41, 12),
(42, 12),
(43, 12),
(44, 12),
(45, 12),
(46, 12),
(47, 12),
(48, 12),
(49, 12),
(50, 12);

INSERT INTO capitulos (numero, nombre, audiolibro, audio) VALUES
(1, 'El niño que sobrevivió', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_1.mp3'),
(2, 'El vidrio que se desvaneció', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_2.mp3'),
(3, 'Las cartas de nadie', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_3.mp3mp3'),
(4, 'El guardián de las llaves', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_4.mp3'),
(5, 'El callejón Diagon', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_5.mp3'),
(6, 'El viaje a través del andén nueve y tres cuartos', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_6.mp3'),
(7, 'El Sombrero Seleccionador', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_7.mp3'),
(8, 'El profesor de Pociones', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_8.mp3'),
(9, 'El duelo a medianoche', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_9.mp3'),
(10, 'Halloween', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_10.mp3'),
(11, 'Quidditch', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_11.mp3'),
(12, 'El espejo de Oesed', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_12.mp3'),
(13, 'Nicolás Flamel', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_13.mp3'),
(14, 'Norberto, el ridgeback noruego', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_14.mp3'),
(15, 'El bosque prohibido', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_15.mp3'),
(16, 'A través de la trampilla', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_16.mp3'),
(17, 'El hombre con dos caras', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_17.mp3'),
(1, 'Canto 01: Concilio de los dioses. Exhortación de Atenea a Telémaco', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_1.mp3'),
(2, 'Canto 02: Telémaco reúne en asamblea al pueblo de Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_2.mp3'),
(3, 'Canto 03: Telémaco viaja a Pilos para informarse sobre su padre', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_3.mp3'),
(4, 'Canto 04: Telémaco viaja a Esparta para informarse sobre su padre', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_4.mp3'),
(5, 'Canto 05: Ulises llega a Esqueria de los feacios', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_5.mp3'),
(6, 'Canto 06: Ulises y Nausícaa', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_6.mp3'),
(7, 'Canto 07: Ulises en el palacio de Alcínoo', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_7.m4a'),
(8, 'Canto 08: Ulises agasajado por los feacios', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_8.mp3'),
(9, 'Canto 09: Ulises cuenta sus aventuras: los cicones, los lotófagos, los cíclopes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_9.mp3'),
(10, 'Canto 10: La isla de Eolo. El palacio de Circe la hechicera', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_10.mp3'),
(11, 'Canto 11: Descenso al Hades', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_11.mp3'),
(12, 'Canto 12: Las sirenas. Escila y Caribdis. La Isla de Helios. Ogigia.', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_12.mp3'),
(13, 'Canto 13: Los feacios despiden a Ulises. Llegada a Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_13.mp3'),
(14, 'Canto 14: Ulises en la majada de Eumeo', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_14.m4a'),
(15, 'Canto 15: Telémaco regresa a Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_15.m4a'),
(16, 'Canto 16: Telémaco reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_16.mp3'),
(17, 'Canto 17: Ulises mendiga entre los pretendientes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_17.mp3'),
(18, 'Canto 18: Los pretendientes vejan a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_18.mp3'),
(19, 'Canto 19: La esclava Euriclea reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_19.mp3'),
(20, 'Canto 20: La última cena de los pretendientes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_20.mp3'),
(21, 'Canto 21: El certamen del arco', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_21.m4a'),
(22, 'Canto 22: La venganza', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_22.mp3'),
(23, 'Canto 23: Penélope reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_23.mp3'),
(24, 'Canto 24. El pacto', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_24.mp3'),
(1, 'Capítulo 1', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_1.mp3'),
(2, 'Capítulo 2', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_2.mp3'),
(3, 'Capítulo 3', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_3.mp3'),
(4, 'Capítulo 4', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_4.mp3'),
(5, 'Capítulo 5', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_5.mp3'),
(6, 'Capítulo 6', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_6.mp3'),
(7, 'Capítulo 7', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_7.mp3'),
(8, 'Capítulo 8', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_8.mp3'),
(9, 'Capítulo 9', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_9.mp3'),
(10, 'Capítulo 10', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_10.mp3'),
(11, 'Capítulo 11', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_11.mp3'),
(12, 'Capítulo 12', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_12.mp3'),
(13, 'Capítulo 13', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_13.mp3'),
(14, 'Capítulo 14', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_14.mp3'),
(15, 'Capítulo 15', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_15.mp3'),
(16, 'Capítulo 16', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_16.mp3'),
(17, 'Capítulo 17', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_17.mp3'),
(18, 'Capítulo 18', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_18.mp3'),
(19, 'Capítulo 19', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_19.mp3'),
(20, 'Capítulo 20', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_20.mp3'),
(21, 'Capítulo 21', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_21.mp3'),
(22, 'Capítulo 22', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_22.mp3'),
(23, 'Capítulo 23', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_23.mp3'),
(24, 'Capítulo 24', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_24.mp3'),
(25, 'Capítulo 25', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_25.mp3'),
(26, 'Capítulo 26', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_26.mp3'),
(27, 'Capítulo 27', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_27.mp3'),
(28, 'Capítulo 28', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_28.mp3'),
(29, 'Capítulo 29', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_29.mp3'),
(30, 'Capítulo 30', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_30.mp3'),
(31, 'Capítulo 31', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_31.mp3'),
(32, 'Capítulo 32', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_32.mp3'),
(33, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_33.mp3'),
(34, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_34.mp3'),
(35, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_35.mp3'),
(36, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_36.mp3'),
(37, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_37.mp3'),
(38, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_38.mp3'),
(39, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_39.mp3'),
(40, 'Capítulo 40', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_40.mp3'),
(41, 'Capítulo 41', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_41.mp3'),
(42, 'Capítulo 42', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_42.mp3'),
(43, 'Capítulo 43', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_43.mp3'),
(44, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_44.mp3'),
(45, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_45.mp3'),
(46, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_46.mp3'),
(47, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_47.mp3'),
(48, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_48.mp3'),
(49, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_49.mp3'),
(50, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_50.mp3'),
(51, 'Capítulo 40', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_51.mp3'),
(52, 'Capítulo 41', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_52.mp3'),
(53, 'Capítulo 42', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_53.mp3'),
(54, 'Capítulo 43', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_54.mp3'),
(55, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_55.mp3'),
(56, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_56.mp3'),
(57, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_57.mp3'),
(58, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_58.mp3'),
(59, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_59.mp3'),
(60, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_60.mp3'),
(61, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_61.mp3'),
(1, 'El Coco', 4, 'https://narrativesarchivos.blob.core.windows.net/audios/ElCoco.mp3'),
(1, 'El Hombre Del Traje Negro', 5, 'https://narrativesarchivos.blob.core.windows.net/audios/ElHombreDelTrajeNegro.mp3'),
(1, 'Popsy', 6, 'https://narrativesarchivos.blob.core.windows.net/audios/Popsy.mp3'),
(1, 'Un Trago De Despedida', 7, 'https://narrativesarchivos.blob.core.windows.net/audios/UnTragoDeDespedida.mp3'),
(1, 'Asesinato en el campo de golf', 8, 'https://narrativesarchivos.blob.core.windows.net/audios/AsesinatoEnElCampoDeGolf.mp3'),
(1, 'Muerte en el Nilo', 9, 'https://narrativesarchivos.blob.core.windows.net/audios/MuerteEnElNilo.mp3'),
(1, 'El misterio del tren azul', 10, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDelTrenAzul.mp3'),
(1, 'Un dios solitario y otros relatos', 11, 'https://narrativesarchivos.blob.core.windows.net/audios/UnDiosSolitarioYOtrosRelatos.mp3'),
(1, 'El club de los martes', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_1.mp3'),
(2, 'La casa del ídolo de Astarté', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_2.mp3'),
(3, 'Lingotes de oro', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_3.mp3'),
(4, 'Manchas de sangre', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_4.mp3'),
(5, 'Móvil versus oportunidad', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_5.mp3'),
(6, 'La huella del pulgar de san Pedro', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_6.mp3'),
(7, 'El geranio azul', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_7.mp3'),
(8, 'La señorita de compañía', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_8.mp3'),
(9, 'Los cuatro sospechosos', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_9.mp3'),
(10, 'Tragedia navideña', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_10.mp3'),
(11, 'La hierba mortal', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_11.mp3'),
(12, 'El caso del bungalow', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_12.mp3'),
(13, 'La ahogada', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_13.mp3'),
(1, 'Un escándalo en Bohemia', 13, 'https://narrativesarchivos.blob.core.windows.net/audios/UnEscandaloEnBohemia.mp3'),
(1, 'El aristócrata solterón', 14, 'https://narrativesarchivos.blob.core.windows.net/audios/ElAristocrataSolteron.mp3'),
(1, 'El misterio de Cooper Beeches', 15, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Caperucita Roja', 16, 'https://narrativesarchivos.blob.core.windows.net/audios/CaperucitaRoja.mp3'),
(1, 'La ratita presumida', 17, 'https://narrativesarchivos.blob.core.windows.net/audios/LaRatitaPresumida.mp3'),
(1, 'Los siete cabritillos y el lobo', 18, 'https://narrativesarchivos.blob.core.windows.net/audios/LosSieteCabritillosYElLobo.mp3'),
(1, 'El gato con botas', 19, 'https://narrativesarchivos.blob.core.windows.net/audios/ElGatoConBotas.mp3'),
(1, 'Las hadas', 20, 'https://narrativesarchivos.blob.core.windows.net/audios/LasHadas.mp3'),
(1, 'Hansel y Gretel', 21, 'https://narrativesarchivos.blob.core.windows.net/audios/HanselYGretel.mp3'),
(1, 'El piojito y la pulguita', 22, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPiojitoYLaPulguita.mp3'),
(1, 'El gigante egoísta', 23, 'https://narrativesarchivos.blob.core.windows.net/audios/ElGiganteEgoista.mp3'),
(1, 'El soldadito de plomo', 24, 'https://narrativesarchivos.blob.core.windows.net/audios/ElSoldaditoDePlomo.mp3'),
(1, 'La princesa y el guisante', 25, 'https://narrativesarchivos.blob.core.windows.net/audios/LaPrincesaYElGuisante.mp3'),
(1, 'La vendedora de fósforos', 26, 'https://narrativesarchivos.blob.core.windows.net/audios/LaVendedoraDeFosforos.mp3'),
(1, 'El último sueño del viejo roble', 27, 'https://narrativesarchivos.blob.core.windows.net/audios/ElUltimoSueñoDelViejoRoble.mp3'),
(1, 'Los tres cerditos y el lobo', 28, 'https://narrativesarchivos.blob.core.windows.net/audios/LosTresCerditosYElLobo.mp3'),
(1, 'El hombre del saco', 29, 'https://narrativesarchivos.blob.core.windows.net/audios/ElHombreDelSaco.mp3'),
(1, 'Las tres naranjitas', 30, 'https://narrativesarchivos.blob.core.windows.net/audios/LasTresNaranjitas.mp3'),
(1, 'Los ladrones arrepentidos', 31, 'https://narrativesarchivos.blob.core.windows.net/audios/LosLadronesArrepentidos.mp3'),
(1, 'El Arte de la Paz', 32, 'https://narrativesarchivos.blob.core.windows.net/audios/ElArteDeLaPaz.mp3'),
(1, 'Las 9 Revelaciones', 33, 'https://narrativesarchivos.blob.core.windows.net/audios/LasNueveRevelaciones.mp3'),
(1, 'Tus pensamientos crean tu vida', 34, 'https://narrativesarchivos.blob.core.windows.net/audios/TusPensamientosCreanTuVida.mp3'),
(1, 'Tú puedes sanar tu vida', 35, 'https://narrativesarchivos.blob.core.windows.net/audios/TuPuedesSanarTuVida.mp3'),
(1, 'La ciencia de hacerse rico', 36, 'https://narrativesarchivos.blob.core.windows.net/audios/LaCienciaDeHacerseRico.mp3'),
(1, 'El poder del ahora', 37, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPoderDelAhora.mp3'),
(1, 'Capítulo 1', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_1.mp3'),
(2, 'Capítulo 2', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_2.mp3'),
(3, 'Capítulo 3', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_3.mp3'),
(4, 'Capítulo 4', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_4.mp3'),
(5, 'Capítulo 5', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_5.mp3'),
(6, 'Capítulo 6', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_6.mp3'),
(7, 'Capítulo 7', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_7.mp3'),
(8, 'Capítulo 8', 38, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaNuevaTierra_8.mp3'),
(1, '101 Formas de Transformar su Vida', 39, 'https://narrativesarchivos.blob.core.windows.net/audios/101FormasDeTransdormarSuVida.mp3'),
(1, 'Al sueño', 40, 'https://narrativesarchivos.blob.core.windows.net/audios/AlSueño.mp3'),
(1, 'Epístola satírica y censoria', 41, 'https://narrativesarchivos.blob.core.windows.net/audios/EpistolaSatiricaYCensoria.mp3'),
(1, 'Memoria inmortal de don Pedro Girón', 42, 'https://narrativesarchivos.blob.core.windows.net/audios/MemoriaInmortalDeDonPedroGiron.mp3'),
(1, 'Conoce la diligencia con que se acerca la muerte', 43, 'https://narrativesarchivos.blob.core.windows.net/audios/ConoceLaDiligenciaConQueSeAcercaLaMuerte.mp3'),
(1, 'Enseña cómo todas las cosas avisan la muerte', 44, 'https://narrativesarchivos.blob.core.windows.net/audios/EnseñaComoTodasLasCosasAvisanLaMuerte.mp3'),
(1, 'Letrilla Satírica «Poderoso Caballero es don Dinero»', 45, 'https://narrativesarchivos.blob.core.windows.net/audios/LetrillaSatiricaPoderosoCaballeroEsDonDinero.mp3'),
(1, 'Romance de Angélica y Medoro', 46, 'https://narrativesarchivos.blob.core.windows.net/audios/RomanceDeAngelicaYMedoro.mp3'),
(1, 'Romance «Servía en Orán al Rey»', 47, 'https://narrativesarchivos.blob.core.windows.net/audios/RomanceServiaEnOranAlRey.mp3'),
(1, 'Romance «Entre los sueltos caballos»', 48, 'https://narrativesarchivos.blob.core.windows.net/audios/RomanceEntreLosSueltosCaballos.mp3'),
(1, 'Letrilla «Ande yo caliente, y ríase la gente»', 49, 'https://narrativesarchivos.blob.core.windows.net/audios/LetrillaAndeYoCalienteYRiaseLaGente.mp3'),
(1, 'Letrilla «Dejadme llorar, orillas del mar»', 50, 'https://narrativesarchivos.blob.core.windows.net/audios/LetrillaDejadmeLlorarOrillasDelMar.mp3'),
(1, 'Capítulos 1 a 3', 51, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeCuervo_1.mp3'),
(2, 'Capítulos 4 a 6', 51, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeCuervo_2.mp3'),
(3, 'Capítulos 7 a 10', 51, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeCuervo_3.mp3'),
(4, 'Capítulos 11 a 13', 51, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeCuervo_4.mp3'),
(5, 'Capítulos 14 a 16', 51, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeCuervo_5.mp3'),
(6, 'Capítulos 17 a 19', 51, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeCuervo_6.mp3'),
(7, 'Capítulos 20 a 22', 51, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeCuervo_7.mp3'),
(1, 'Capítulos 1 a 3', 52, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeLeopardo_1.mp3'),
(2, 'Capítulos 4 a 6', 52, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeLeopardo_2.mp3'),
(3, 'Capítulos 7 a 9', 52, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeLeopardo_3.mp3'),
(4, 'Capítulos 10 a 12', 52, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeLeopardo_4.mp3'),
(5, 'Capítulos 13 a 15', 52, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeLeopardo_5.mp3'),
(6, 'Capítulos 16 a 18', 52, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeLeopardo_6.mp3'),
(7, 'Capítulos 19 a 21', 52, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeLeopardo_7.mp3'),
(1, 'Capítulos 1 a 3', 53, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeSerpiente_1.mp3'),
(2, 'Capítulos 4 a 6', 53, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeSerpiente_2.mp3'),
(3, 'Capítulos 7 a 9', 53, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeSerpiente_3.mp3'),
(4, 'Capítulos 10 a 12', 53, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeSerpiente_4.mp3'),
(5, 'Capítulos 13 a 16', 53, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeSerpiente_5.mp3'),
(6, 'Capítulos 17 a 20', 53, 'https://narrativesarchivos.blob.core.windows.net/audios/ElPrincipeSerpiente_6.mp3'),
(1, 'Capítulos 1 a 4', 54, 'https://narrativesarchivos.blob.core.windows.net/audios/LaPrincesaDeHielo_1.mp3'),
(2, 'Capítulos 5 a 12', 54, 'https://narrativesarchivos.blob.core.windows.net/audios/LaPrincesaDeHielo_2.mp3'),
(1, 'Capítulos 1 y 2', 55, 'https://narrativesarchivos.blob.core.windows.net/audios/EncajesYPecados_1.mp3'),
(2, 'Capítulos 3 a 6', 55, 'https://narrativesarchivos.blob.core.windows.net/audios/EncajesYPecados_2.mp3'),
(3, 'Capítulos 7 a 10', 55, 'https://narrativesarchivos.blob.core.windows.net/audios/EncajesYPecados_3.mp3'),
(4, 'Capítulos 11 a 14', 55, 'https://narrativesarchivos.blob.core.windows.net/audios/EncajesYPecados_4.mp3'),
(5, 'Capítulos 15 a 18', 55, 'https://narrativesarchivos.blob.core.windows.net/audios/EncajesYPecados_5.mp3'),
(6, 'Capítulos 19 a 23', 55, 'https://narrativesarchivos.blob.core.windows.net/audios/EncajesYPecados_6.mp3'),
(7, 'Capítulos 24 a 33', 55, 'https://narrativesarchivos.blob.core.windows.net/audios/EncajesYPecados_7.mp3'),
(1, 'Capítulos 1 y 2', 56, 'https://narrativesarchivos.blob.core.windows.net/audios/Fugitiva_1.mp3'),
(2, 'Capítulos 3 a 7', 56, 'https://narrativesarchivos.blob.core.windows.net/audios/Fugitiva_2.mp3'),
(3, 'Capítulos 8 a 12', 56, 'https://narrativesarchivos.blob.core.windows.net/audios/Fugitiva_3.mp3'),
(4, 'Capítulos 13 a 18', 56, 'https://narrativesarchivos.blob.core.windows.net/audios/Fugitiva_4.mp3'),
(5, 'Capítulos 19 a 25', 56, 'https://narrativesarchivos.blob.core.windows.net/audios/Fugitiva_5.mp3'),
(6, 'Capítulos 26 a 30', 56, 'https://narrativesarchivos.blob.core.windows.net/audios/Fugitiva_6.mp3'),
(1, 'Capítulos 1 a 3', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_1.mp3'),
(2, 'Capítulos 4 a 7', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_2.mp3'),
(3, 'Capítulos 8 a 10', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_3.mp3'),
(4, 'Capítulos 11 a 14', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_4.mp3'),
(5, 'Capítulos 15 a 18', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_5.mp3'),
(6, 'Capítulos 19 a 22', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_6.mp3'),
(7, 'Capítulos 23 y 25', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_7.mp3'),
(8, 'Capítulos 26 y 28', 57, 'https://narrativesarchivos.blob.core.windows.net/audios/Indomito_8.mp3'),
(1, 'Capítulos 1 a 3', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_1.mp3'),
(2, 'Capítulos 4 a 6', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_2.mp3'),
(3, 'Capítulos 7 a 9', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_3.mp3'),
(4, 'Capítulos 10 a 12', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_4.mp3'),
(5, 'Capítulos 13 a 15', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_5.mp3'),
(6, 'Capítulos 16 a 18', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_6.mp3'),
(7, 'Capítulos 19 y 20', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_7.mp3'),
(8, 'Capítulos 21 y 22', 58, 'https://narrativesarchivos.blob.core.windows.net/audios/Prohibido_8.mp3'),
(1, 'Capítulos 1 a 5', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_1.mp3'),
(2, 'Capítulos 6 a 8', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_2.mp3'),
(3, 'Capítulos 9 a 12', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_3.mp3'),
(4, 'Capítulos 13 a 16', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_4.mp3'),
(5, 'Capítulos 17 a 20', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_5.mp3'),
(6, 'Capítulos 21 a 23', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_6.mp3'),
(7, 'Capítulos 24 y 26', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_7.mp3'),
(8, 'Capítulos 27 y 29', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_8.mp3'),
(9, 'Capítulos 30 y 33', 59, 'https://narrativesarchivos.blob.core.windows.net/audios/Hechicera_9.mp3'),
(1, 'Capítulos 1 a 3', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_1.mp3'),
(2, 'Capítulos 4 y 5', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_2.mp3'),
(3, 'Capítulos 6 y 7', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_3.mp3'),
(4, 'Capítulos 8 y 9', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_4.mp3'),
(5, 'Capítulos 10 y 11', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_5.mp3'),
(6, 'Capítulos 12 y 13', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_6.mp3'),
(7, 'Capítulos 14 y 15', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_7.mp3'),
(8, 'Capítulos 16 a 18', 60, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter2_8.mp3'),
(1, 'Capítulos 1 a 3', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_1.mp3'),
(2, 'Capítulos 4 y 5', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_2.mp3'),
(3, 'Capítulos 6 y 7', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_3.mp3'),
(4, 'Capítulos 8 y 9', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_4.mp3'),
(5, 'Capítulos 10 y 11', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_5.mp3'),
(6, 'Capítulos 12 y 13', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_6.mp3'),
(7, 'Capítulos 14 y 15', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_7.mp3'),
(8, 'Capítulos 16 y 17', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_8.mp3'),
(9, 'Capítulos 18 a 20', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_9.mp3'),
(10, 'Capítulos 21 y 22', 61, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter3_10.mp3'),
(1, 'Capítulos 1 a 4', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_1.mp3'),
(2, 'Capítulos 5 a 7', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_2.mp3'),
(3, 'Capítulos 8 y 9', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_3.mp3'),
(4, 'Capítulos 10 a 12', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_4.mp3'),
(5, 'Capítulos 13 y 14', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_5.mp3'),
(6, 'Capítulos 15 y 16', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_6.mp3'),
(7, 'Capítulos 17 y 18', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_7.mp3'),
(8, 'Capítulos 19 y 20', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_8.mp3'),
(9, 'Capítulos 21 y 22', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_9.mp3'),
(10, 'Capítulos 23 y 24', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_10.mp3'),
(11, 'Capítulos 25 y 26', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_11.mp3'),
(12, 'Capítulos 27 y 28', 62, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter4_12.mp3'),
(1, 'Capítulos 1 a 3', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_1.mp3'),
(2, 'Capítulos 4 a 6', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_2.mp3'),
(3, 'Capítulos 8 a 11', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_3.mp3'),
(4, 'Capítulos 11 a 13', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_4.mp3'),
(5, 'Capítulos 14 a 17', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_5.mp3'),
(6, 'Capítulos 18 a 21', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_6.mp3'),
(7, 'Capítulos 22 a 24', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_7.mp3'),
(8, 'Capítulos 25 a 31', 63, 'https://narrativesarchivos.blob.core.windows.net/audios/MentesPoderosas_8.mp3'),
(1, 'Capítulos 1 y 2', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_1.mp3'),
(2, 'Capítulos 3 a 5', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_2.mp3'),
(3, 'Capítulos 6 a 8', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_3.mp3'),
(4, 'Capítulos 9 y 10', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_4.mp3'),
(5, 'Capítulos 11 a 16', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_5.mp3'),
(6, 'Capítulos 17 a 20', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_6.mp3'),
(7, 'Capítulos 21 a 24', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_7.mp3'),
(8, 'Capítulos 25 a 27', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_8.mp3'),
(9, 'Capítulo 28', 64, 'https://narrativesarchivos.blob.core.windows.net/audios/NuncaOlvidan_9.mp3'),
(1, 'Capítulos 1 y 2', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_1.mp3'),
(2, 'Capítulos 3 a 5', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_2.mp3'),
(3, 'Capítulos 6 a 8', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_3.mp3'),
(4, 'Capítulos 9 a 11', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_4.mp3'),
(5, 'Capítulos 12 a 14', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_5.mp3'),
(6, 'Capítulos 15 y 16', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_6.mp3'),
(7, 'Capítulos 18 a 20', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_7.mp3'),
(8, 'Capítulos 21 a 24', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_8.mp3'),
(9, 'Capítulos 25 a 27', 65, 'https://narrativesarchivos.blob.core.windows.net/audios/UnaLuzIncierta_9.mp3'),
(1, 'La puerta equivocada', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_1.mp3'),
(2, 'Digory y su tío', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_2.m4a'),
(3, 'El Bosque entre los Mundos', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_3.m4a'),
(4, 'La campana y el martillo', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_4.m4a'),
(5, 'La palabra deplorable', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_5.m4a'),
(6, 'El principio de los problemas del tío Andrew', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_6.m4a'),
(7, 'Lo que sucedió ante la puerta principal', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_7.m4a'),
(8, 'La pelea junto al farol', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_8.m4a'),
(9, 'La creación de Narnia', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_9.m4a'),
(10, 'El primer chiste y otros asuntos', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_10.m4a'),
(11, 'Digory y su tío tienen problemas', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_11.m4a'),
(12, 'La aventura de Fresón', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_12.m4a'),
(13, 'Un encuentro inesperado', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_13.m4a'),
(14, 'Plantando el árbol', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_14.m4a'),
(15, 'El fin de esta historia y el inicio de todas las demás', 66, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia1_15.m4a'),
(1, 'Lucy se mete en el armario', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_1.mp3'),
(2, 'Lo que encontró Lucy', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_2.m4a'),
(3, 'Edmund y el armario', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_3.m4a'),
(4, 'Delicias turcas', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_4.m4a'),
(5, 'De vuelta a este lado de la puerta', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_5.m4a'),
(6, 'En el interior del bosque', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_6.m4a'),
(7, 'Un día con los castores', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_7.m4a'),
(8, 'Lo que sucedió después de cenar', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_8.m4a'),
(9, 'En casa de la bruja', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_9.m4a'),
(10, 'El hechizo empieza a romperse', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_10.m4a'),
(11, 'Aslan está cada vez más cerca', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_11.m4a'),
(12, 'La primera batalla de Peter', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_12.m4a'),
(13, 'Magia Insondable de los albores del tiempo', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_13.m4a'),
(14, 'El triunfo de la bruja', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_14.m4a'),
(15, 'Magia Más Insondable de antes de los albores del tiempo', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_15.m4a'),
(16, 'Lo que sucedió con las estatuas', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_16.m4a'),
(17, 'La cacería del Ciervo Blanco', 67, 'https://narrativesarchivos.blob.core.windows.net/audios/Narnia2_17.m4a');
