INSERT INTO autores (nombre) VALUES
('Anónimo'),
('J. K. Rowling'),
('Homero'),
('Jane Austen'),
('Stephen King'),
('Agatha Christie'),
('Arthur Conan Doyle'),
('Charles Perrault'),
('Hermanos Grimm'),
('Oscar Wilde'),
('Hans Christian Andersen');

INSERT INTO generos (nombre) VALUES
('Romance'),
('Aventuras'),
('Fantasía'),
('Ciencia ficción'),
('Terror'),
('Infantil'),
('Misterio'),
('Histórico'),
('Mitología'),
('Humor'),
('Autoayuda'),
('Poesía');

INSERT INTO audiolibros (titulo, autor, descripcion, img) VALUES
('Harry Potter y la piedra filosofal', 2, '«Con las manos temblorosas, Harry le dio la vuelta al sobre y vio un sello de lacre púrpura con un escudo de armas: un león, un águila, un tejón y una serpiente, que rodeaban una gran letra H.»
Harry Potter nunca ha oído hablar de Hogwarts hasta que empiezan a caer cartas en el felpudo del número 4 de Privet Drive. Llevan la dirección escrita con tinta verde en un sobre de pergamino amarillento con un sello de lacre púrpura, y sus horripilantes tíos se apresuran a confiscarlas. Más tarde, el día que Harry cumple once años, Rubeus Hagrid, un hombre gigantesco cuyos ojos brillan como escarabajos negros, irrumpe con una noticia extraordinaria: Harry Potter es un mago, y le han concedido una plaza en el Colegio Hogwarts de Magia y Hechicería. ¡Está a punto de comenzar una aventura increíble!', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HarryPotter1.jpeg'),
('La Odisea', 3, 'Este poema épico, compuesto por veinticuatro cantos, narra la vuelta a casa, tras una década de guerra, del héroe griego Odiseo (Ulises, en latín). Para el regreso a Itaca, su hogar y su reino, y tras una ofensa al dios Poseidón, Odiseo dedica otros diez años, condenado a navegar sin rumbo sufriendo diversas vicisitudes.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaOdisea.png'),
('Orgullo y Prejuicio', 4, '«Es una verdad universalmente aceptada que todo soltero en posesión de una gran fortuna necesita una esposa ». Nueva traducción ilustrada de la novela de Jane Austen. Este comienzo, que, junto con el de Ana Karénina, es quizás uno de los más famosos de la historia de la literatura, nos introduce sabiamente en el mundo de Jane Austen y de su novela más emblemática. Orgullo y prejuicio, publicada en 1813 tras el éxito de Juicio y sentimiento, reúne de forma ejemplar sus temas recurrentes y su visión inimitable en la historia de las cinco hijas de la señora Bennett, que no tiene otro objetivo en su vida que conseguir una buena boda para todas ellas. Dos ricos jóvenes, el señor Bingley y el señor Darcy, aparecen en su punto de mira e inmediatamente se ven señalados como posibles  presas . De hecho, la relación entre la hija mayor, Jane, y el señor Bingley parece muy prometedora pero, por influencia del arrogante señor Darcy, se frustran todas las esperanzas. La intervención de Elizabeth, la hija segunda, perspicaz, consciente de su valor, y algo rebelde, determinará el rumbo de la novela. En ella el opresivo ambiente de la familia, la presión del matrimonio, la diferencia de clases, el fantasma de la pobreza y la delicada sensibilidad de una heroína decidida, pero no libre de errores de juicio y dudas de comportamiento, se conjugan para crear una obra maestra leída a lo largo de más de dos siglos.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/OrgulloYPrejuicio.jpg'),
('El Coco', 5, 'La estudiante de secundaria Sadie Harper (Sophie Tatcher) y su hermana menor Sawyer (Vivien Lyra Blair) se están recuperando de la reciente muerte de su madre y no reciben mucho apoyo de su padre, Will (Chris Messina), un terapeuta que está lidiando con su propio dolor.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElCoco.jpg'),
('El Hombre Del Traje Negro', 5, 'A los 90 años y antes de que le llegue la muerte, Gary decide poner por escrito lo que le sucedió en 1914, cuando sólo tenía 9, para que quede constancia. Un encuentro paranormal con un hombre con un traje negro de tres piezas mientras pescaba truchas en la orilla de un solitario río.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElHombreDelTrajeNegro.jpg'),
('Popsy', 5, 'Sheridan es un adicto al juego quien ha contraído una enorme deuda. Para pagarla, secuestra a niños a petición de un mafioso. El niño que secuestra resulta ser un vampiro al igual que su Abuelito (Popsy en inglés) que no esta dispuesto a dejar que Sheridan huya con su nieto.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/Popsy.jpg'),
('Un Trago De Despedida', 5, 'Cierta noche de invierno, en un bar, varios parroquianos mantienen sus charlas habituales. Cuando están a punto de cerrar, un hombre muy alarmado entra pidiendo ayuda: su coche ha quedado atrapado por la nieve en la carretera que conduce a Jerusalem’s Lot (o Salem’s lot), un pueblo «aparentemente» abandonado.
Lo que sobrecoge a esos parroquianos es que la mujer y la hija del conductor han quedado en el interior del vehículo. Inmediatamente se ponen en marcha, aunque quizá cuando lleguen sea tarde.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElUmbralDeLaNoche.jpg'),
('Asesinato en el campo de golf', 5, 'Hércules Poirot recibe una carta de Paul Renauld, quien le dice que teme por su vida y le urge a que acuda en su ayuda. Así, junto con su amigo el capitán Hastings, el detective se dirige rápido al norte de Francia para prestar sus servicios al nuevo cliente. Sin embargo, llegan demasiado tarde: el cuerpo de Renauld yace apuñalado en medio de un campo de golf.
Mientras Poirot investiga la escena del crimen y a los posibles sospechosos, descubre otro cuerpo asesinado de la misma manera que el primero, y con la misma arma. ¿Qué tienen en común estos hombres? ¿Quién los ha matado? ¿Y por qué Poirot no deja de pensar en un crimen cometido años atrás?', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/AsesinatoEnElCampoDeGolf.jpg'),
('Muerte en el Nilo', 6, 'Un célebre caso que pone a prueba la extrema lucidez de Hércules Poirot.
Durante unas placenteras vacaciones en Egipto, el detective Hércules Poirot coincide con Linnet y Simon, unos conocidos suyos que están de luna de miel en el país de los faraones.
El encanto de tan maravillosos días se rompe cuando una mañana, en el transcurso de un crucero por el Nilo, la bella Linnet aparece muerta de un disparo en la cabeza.
¿Será capaz Poirot de encontrar al asesino de la joven esposa? ¿Será capaz de discernir entre imaginación y realidad, aun estando a bordo la ex pareja de Simon, empeñada desde el mismo día de la boda en arruinar su matrimonio con la desafortunada Linnet?
El misterio está servido.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/MuerteEnElNilo.jpg'),
('El misterio del tren azul', 6, 'El Tren Azul con destino a Niza transporta una valiosa carga: el mayor rubí del mundo, el "Corazón de Fuego", un regalo de un magnate americano del petróleo para su querida hija, Ruth Kettering. Pero al llegar a la Costa Azul, se descubre que la propietaria de la joya ha sido brutalmente asesinada y que el rubí ha desaparecido. El millonario Rufus Van Aldin, muy afectado por la muerte de su heredera, contrata al detective Hercule Poirot para que resuelva el estremecedor suceso. El caso irá adquiriendo una creciente complejidad a medida que Poirot descubra el turbulento pasado de la víctima: su recientemente frustrado matrimonio, la tensa relación que mantenía con su padre y la existencia de un ex pretendiente con quien debía encontrarse en Niza. Es un caso aparentemente imposible de resolver, donde todos son sospechosos y ningún indicio conduce al culpable. Una historia de intriga apasionante donde nada es lo que parece que mantendrá al lector sin aliento hasta la última página. "Hercule Poirot no es un toxicómano atormentado, como Sherlock Holmes, o un glotón desencantado, como Pepe Carvalho, o un alcohólico cínico, como Philip Marlowe. Es un sibarita que vive como un pachá e idolatra el clasismo británico." Del Prólogo de Enric González', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElMisterioDelTrenAzul.jpg'),
('Un dios solitario y otros relatos', 6, 'Como muchos de sus contemporáneos, Agatha Christie escribió relatos para diversas revistas en los años veinte y treinta, y casi todos ellos acabaron incluidos más tarde en libros recopilatorios. Este libro, casi una pieza de coleccionista, muestra a la maestra del crimen en su etapa de formación, y sus lectores podrán comprobar una vez más su gran dominio de la caracterización y su habilidad para los desenlaces imprevistos', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/UnDiosSolitarioYOtrosRelatos.jpg'),
('Miss Marple y 13 problemas', 6, '"¿Qué le parece si formásemos un club? Lo llamaremos el Club de los Martes. Nos reuniremos y cada uno deberá exponer un problema real y los demás competiremos para solucionarlo". A partir de esta conversación nacen trece magníficas historias policíacas.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/MissMarpleY13Problemas.jpg'),
('Un escándalo en Bohemia', 7, 'Escándalo en Bohemia es el primero de los 56 relatos cortos sobre Sherlock Holmes escrito por Arthur Conan Doyle y la primera historia de Sherlock Holmes ilustrada por Sidney Paget. Fue publicado originalmente en The Strand Magazine y posteriormente recogido en la colección Las aventuras de Sherlock Holmes. Sherlock Holmes es llamado por un caballero enmascarado. Se presenta como el conde Von Kramm, un agente de un cliente adinerado, pero Holmes deduce rápidamente que se trata de Wilhelm Gottsreich Sigismond von Ormstein, gran duque de Cassel-Felstein y rey hereditario de Bohemia. El rey, arrancándose la máscara, lo admite.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/UnEscandaloEnBohemia.jpg'),
('El aristócrata solterón', 7, 'El Aristócrata Solterón relata el caso de la extraña desaparición de la rica heredera Hatty Doran. Hija única del multimillonario Aloysius Doran, se ha esfumado tras su matrimonio con el citado Lord St. Simon, segundo hijo del duque de Balmoral y perteneciente a la más rancia aristocracia de Inglaterra. A pesar de la poca simpatía que inspira a Holmes el estirado personaje, el caso le interesa, y se hace cargo de él.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElAristocrataSolteron.jpg'),
('El misterio de Cooper Beeches', 7, 'Violet Hunter acude a la consulta de Holmes después de que le ofrezcan un puesto de institutriz sujeto a raras condiciones, incluyendo una que la obliga a cortarse el pelo. El sueldo es extremadamente elevado, de 120 libras, y, por ende, decide aceptarlo, aunque Holmes le aconseja que le llame si lo necesita. Tras varios sucesos extraños, incluido el descubrimiento de una zona sellada de la casa, se decide a llamarle. Holmes descubre que habían mantenido a alguien preso en esa parte de la propiedad, pero, cuando entra acompañado de Watson y la propia Hunter, se topa con que está vacía. Los acusan de liberar a la prisionera, que era la hija de la empleador de Hunter, y este manda al perro a perseguirlos; sin embargo, el animal lo ataca a él. Se descubre que a Hunter la habían contratado para hacerse pasar por la hija de su empleador, de modo que su prometido se creyera que ella ya no estaba interesada en verla; la hija, no obstante, se había escapado y conseguido casarse.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElMisterioDeCooperBeeches.jpg'),
('Caperucita Roja', 8, 'Caperucita Roja es una niña que quería mucho a su abuela; un día su madre le da una cesta con comida para que se la lleve a la abuela, que está enferma y vive en una casa algo lejos de ellas. ​ En el camino se encuentra con el Lobo Feroz que la reta a una carrera hasta la casa de la abuela.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/CaperucitaRoja.jpg'),
('La ratita presumida', 8, 'La RATITA se quejaba de una vida aburrida y llena de monotonía. No se esperaba que un lazo revolucionaría tanto su día de la forma en que lo hizo. A partir de ahí, un séquito de pretendientes intentaran seducirla para poder casarse con ella.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaRatitaPresumida.jpg'),
('Los siete cabritillos y el lobo', 8, 'Mamá cabra y sus siete cabritillos vivían en una pequeña casa en el bosque. Un día, mamá cabra, llamó a sus pequeños y les dijo: »Voy a recolectar bayas. No abráis la puerta a nadie, a nadie os digo. Y recordad que el lobo se disfraza: pero si estáis atentos, lo reconoceréis por la voz y por las patas negras».', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LosSieteCabritillosYElLobo.jpg'),
('El gato con botas', 8, 'Había una vez un molinero que dejó en herencia a sus hijos un molino, un asno y un gato. Al pequeño le tocó el gato, que era muy listo. El gato le dijo a su nuevo dueño que si le daba unas botas y un saco, no se arrepentiría. ¿Qué es lo que tramaba el felino?
Había una vez un molinero que dejó en herencia a sus hijos un molino, un asno y un gato. Al pequeño le tocó el gato, que era muy listo. El gato le dijo a su nuevo dueño que si le daba unas botas y un saco, no se arrepentiría. ¿Qué es lo que tramaba el felino?', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElGatoConBotas.jpg'),
('Las hadas', 8, 'Este cuento trata de una mujer viuda con dos hijas. La madre prefería a su hija mayor y a la menor la detestaba, encargandole trabajos domésticos muy pesados. Un día, la hija menor fue a un arroyo donde un hada le regala un don maravilloso de convertir las palabras en flores y piedras preciosas.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LasHadas.jpg'),
('Hansel y Gretel', 9, 'Dos hermanos, una niña llamada Gretel y un niño llamado Hansel, hijos de un leñador, viven con su padre y su madrastra cerca de un bosque, la madrastra odiaba a los niños. Como eran muy pobres, a la madrastra se le ocurrió la idea de llevar a los niños a la parte más profunda del bosque y dejarlos allí abandonados.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/HanselYGretel.jpg'),
('El piojito y la pulguita', 9, 'Un piojito y una pulguita hacían vida en común y cocían su cerveza en una cáscara de huevo. He aquí que el piojito se cayó dentro y se quemó. Ante aquella desgracia, la pulguita se puso a llorar a voz en grito. Al oírla, preguntó la puerta de la habitación: “¿Por qué lloras, Pulguita?” – “Porque Piojito se ha quemado. Y la noticia irá corriendo de boca en boca, se enterarán la escobita, el fogoncito, el arbolillo, la muchachita y la fuentecita.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElPiojitoYLaPulguita.jpg'),
('El gigante egoísta', 10, 'Los niños del pueblo juegan en el amplio jardin de la casa de un Gigante. Harto de sus voces y de sus risas, el Gigante, un ser solitario y egoista, levanta un muro tan alto que los pequeños no pueden saltarlo. Desde ese momento ya no regresa a su jardin la primavera.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElGiganteEgoista.jpg'),
('El soldadito de plomo', 11, 'En la narración de Hans Christian Andersen, el soldado de una sola pierna se enamora de la bailarina de palacio, es arrancado de su pequeño mundo, comienza un viaje aventurero en un barco de papel y, finalmente, regresa a casa, donde se le depara un final agridulce.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElSoldaditoDePlomo.jpg'),
('La princesa y el guisante', 11, 'La protagonista, Amira, hija del rey Mustafá de Arabia, decide huir para evitar que su padre la case con un sultán que ella no conoce. Lo mismo le pasa al príncipe Arnaldo cuando su madre le obliga a casarse con la joven que sea capaz de notar la presencia de un guisante escondido bajo siete colchones.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElSoldaditoDePlomo.jpg'),
('La vendedora de fósforos', 11, 'La vendedora de fósforos de Andersen, el burro de Bresson, la relación entre un guerrillero alemán y una pianista argentina, y Helmut Lachenmann tratando de montar una ópera con la orquesta del Teatro Colón en huelga. Marie y Walter intentarán con su hija vivir en el medio de todo eso.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LaVendedoraDeFosforos.jpg'),
('El último sueño del viejo roble', 11, 'Trata la historia de un viejo roble que vive junto a un puerto pesquero. Tiene 365 años y a su alrededor, cada verano, revolotean las moscas que solo viven un día. Llega el otoño y las hojas comienzan a caer y el árbol y los animales se preparan para los largos meses de invierno.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElUltimoSueñoDelViejoRoble.jpg'),
('Los tres cerditos y el lobo', 1, 'Los tres cerditos y el lobo
Cada uno de los tres cerditos tiene una personalidad distinta. El encuentro de cada uno de ellos con el lobo la sacará a relucir.
El lobo de los tres cerditos
A lo mejor, el lobo de los tres cerditos no era tan malo. Cuenta esta historia que cuando eran pequeños los tres cerditos y el lobo se encontraron en una playa y algo ocurrió...', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LosTresCerditosYElLobo.jpg'),
('El hombre del saco', 1, 'Con trece años, es víctima de un violento depredador sexual infantil que le destroza una vida de sueños e intenta matarla. Tras una vida al margen de la ley, ingresa en prisión acusada de perpetrar una serie de atracos a entidades bancarias, en la que pasara ocho años de su vida.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/ElHombreDelSaco.jpg'),
('Las tres naranjitas', 1, 'Un príncipe sale de palacio en busca de esposa. Un anciano le indica que ruta seguir y cómo enfrentar los peligros del camino. Tras fracasar en dos oportunidades, a la tercera encuentra su princesa, aunque aún ha pasar otras peripecias antes de su boda.', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LasTresNaranjitas.jpg'),
('Los ladrones arrepentidos', 1, 'Cuentos y Leyendas Populares', 
'https://narrativesarchivos.blob.core.windows.net/imagenes/LosLadronesArrepentidos.jpg');

INSERT INTO genero_audiolibro (audiolibro, genero) VALUES
(3, 1),
(1, 3),
(4, 5),
(5, 5),
(6, 5),
(7, 5),
(16, 6),
(17, 6),
(18, 6),
(19, 6),
(20, 6),
(21, 6),
(22, 6),
(23, 6),
(24, 6),
(25, 6),
(26, 6),
(27, 6),
(28, 6),
(29, 6),
(30, 6),
(31, 6),
(8, 7),
(9, 7),
(10, 7),
(11, 7),
(12, 7),
(13, 7),
(14, 7),
(15, 7),
(2, 8);

INSERT INTO capitulos (numero, nombre, audiolibro, audio) VALUES
(1, 'El niño que sobrevivió', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_1.mp3'),
(2, 'El vidrio que se desvaneció', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_2.mp3'),
(3, 'Las cartas de nadie', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_3.mp3mp3'),
(4, 'El guardián de las llaves', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_4.mp3'),
(5, 'El callejón Diagon', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_5.mp3'),
(6, 'El viaje a través del andén nueve y tres cuartos', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_6.mp3'),
(7, 'El Sombrero Seleccionador', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_7.mp3'),
(8, 'El profesor de Pociones', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_8.mp3'),
(9, 'El duelo a medianoche', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_9.mp3'),
(10, 'Halloween', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_10.mp3'),
(11, 'Quidditch', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_11.mp3'),
(12, 'El espejo de Oesed', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_12.mp3'),
(13, 'Nicolás Flamel', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_13.mp3'),
(14, 'Norberto, el ridgeback noruego', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_14.mp3'),
(15, 'El bosque prohibido', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_15.mp3'),
(16, 'A través de la trampilla', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_16.mp3'),
(17, 'El hombre con dos caras', 1, 'https://narrativesarchivos.blob.core.windows.net/audios/HarryPotter1_17.mp3'),
(1, 'Canto 01: Concilio de los dioses. Exhortación de Atenea a Telémaco', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_1.mp3'),
(2, 'Canto 02: Telémaco reúne en asamblea al pueblo de Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_2.mp3'),
(3, 'Canto 03: Telémaco viaja a Pilos para informarse sobre su padre', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_3.mp3'),
(4, 'Canto 04: Telémaco viaja a Esparta para informarse sobre su padre', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_4.mp3'),
(5, 'Canto 05: Ulises llega a Esqueria de los feacios', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_5.mp3'),
(6, 'Canto 06: Ulises y Nausícaa', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_6.mp3'),
(7, 'Canto 07: Ulises en el palacio de Alcínoo', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_7.m4a'),
(8, 'Canto 08: Ulises agasajado por los feacios', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_8.mp3'),
(9, 'Canto 09: Ulises cuenta sus aventuras: los cicones, los lotófagos, los cíclopes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_9.mp3'),
(10, 'Canto 10: La isla de Eolo. El palacio de Circe la hechicera', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_10.mp3'),
(11, 'Canto 11: Descenso al Hades', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_11.mp3'),
(12, 'Canto 12: Las sirenas. Escila y Caribdis. La Isla de Helios. Ogigia.', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_12.mp3'),
(13, 'Canto 13: Los feacios despiden a Ulises. Llegada a Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_13.mp3'),
(14, 'Canto 14: Ulises en la majada de Eumeo', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_14.m4a'),
(15, 'Canto 15: Telémaco regresa a Ítaca', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_15.m4a'),
(16, 'Canto 16: Telémaco reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_16.mp3'),
(17, 'Canto 17: Ulises mendiga entre los pretendientes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_17.mp3'),
(18, 'Canto 18: Los pretendientes vejan a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_18.mp3'),
(19, 'Canto 19: La esclava Euriclea reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_19.mp3'),
(20, 'Canto 20: La última cena de los pretendientes', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_20.mp3'),
(21, 'Canto 21: El certamen del arco', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_21.m4a'),
(22, 'Canto 22: La venganza', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_22.mp3'),
(23, 'Canto 23: Penélope reconoce a Ulises', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_23.mp3'),
(24, 'Canto 24. El pacto', 2, 'https://narrativesarchivos.blob.core.windows.net/audios/LaOdisea_24.mp3'),
(1, 'Capítulo 1', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_1.mp3'),
(2, 'Capítulo 2', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_2.mp3'),
(3, 'Capítulo 3', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_3.mp3'),
(4, 'Capítulo 4', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_4.mp3'),
(5, 'Capítulo 5', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_5.mp3'),
(6, 'Capítulo 6', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_6.mp3'),
(7, 'Capítulo 7', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_7.mp3'),
(8, 'Capítulo 8', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_8.mp3'),
(9, 'Capítulo 9', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_9.mp3'),
(10, 'Capítulo 10', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_10.mp3'),
(11, 'Capítulo 11', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_11.mp3'),
(12, 'Capítulo 12', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_12.mp3'),
(13, 'Capítulo 13', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_13.mp3'),
(14, 'Capítulo 14', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_14.mp3'),
(15, 'Capítulo 15', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_15.mp3'),
(16, 'Capítulo 16', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_16.mp3'),
(17, 'Capítulo 17', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_17.mp3'),
(18, 'Capítulo 18', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_18.mp3'),
(19, 'Capítulo 19', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_19.mp3'),
(20, 'Capítulo 20', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_20.mp3'),
(21, 'Capítulo 21', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_21.mp3'),
(22, 'Capítulo 22', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_22.mp3'),
(23, 'Capítulo 23', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_23.mp3'),
(24, 'Capítulo 24', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_24.mp3'),
(25, 'Capítulo 25', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_25.mp3'),
(26, 'Capítulo 26', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_26.mp3'),
(27, 'Capítulo 27', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_27.mp3'),
(28, 'Capítulo 28', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_28.mp3'),
(29, 'Capítulo 29', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_29.mp3'),
(30, 'Capítulo 30', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_30.mp3'),
(31, 'Capítulo 31', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_31.mp3'),
(32, 'Capítulo 32', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_32.mp3'),
(33, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_33.mp3'),
(34, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_34.mp3'),
(35, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_35.mp3'),
(36, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_36.mp3'),
(37, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_37.mp3'),
(38, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_38.mp3'),
(39, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_39.mp3'),
(40, 'Capítulo 40', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_40.mp3'),
(41, 'Capítulo 41', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_41.mp3'),
(42, 'Capítulo 42', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_42.mp3'),
(43, 'Capítulo 43', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_43.mp3'),
(44, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_44.mp3'),
(45, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_45.mp3'),
(46, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_46.mp3'),
(47, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_47.mp3'),
(48, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_48.mp3'),
(49, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_49.mp3'),
(50, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_50.mp3'),
(51, 'Capítulo 40', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_51.mp3'),
(52, 'Capítulo 41', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_52.mp3'),
(53, 'Capítulo 42', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_53.mp3'),
(54, 'Capítulo 43', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_54.mp3'),
(55, 'Capítulo 33', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_55.mp3'),
(56, 'Capítulo 34', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_56.mp3'),
(57, 'Capítulo 35', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_57.mp3'),
(58, 'Capítulo 36', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_58.mp3'),
(59, 'Capítulo 37', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_59.mp3'),
(60, 'Capítulo 38', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_60.mp3'),
(61, 'Capítulo 39', 3, 'https://narrativesarchivos.blob.core.windows.net/audios/OrgulloYPrejuicio_61.mp3'),
(1, 'El Coco', 4, 'https://narrativesarchivos.blob.core.windows.net/audios/ElCoco.mp3'),
(1, 'El Hombre Del Traje Negro', 5, 'https://narrativesarchivos.blob.core.windows.net/audios/ElHombreDelTrajeNegro.mp3'),
(1, 'Popsy', 6, 'https://narrativesarchivos.blob.core.windows.net/audios/Popsy.mp3'),
(1, 'Un Trago De Despedida', 7, 'https://narrativesarchivos.blob.core.windows.net/audios/UnTragoDeDespedida.mp3'),
(1, 'Asesinato en el campo de golf', 8, 'https://narrativesarchivos.blob.core.windows.net/audios/AsesinatoEnElCampoDeGolf.mp3'),
(1, 'Muerte en el Nilo', 9, 'https://narrativesarchivos.blob.core.windows.net/audios/MuerteEnElNilo.mp3'),
(1, 'El misterio del tren azul', 10, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDelTrenAzul.mp3'),
(1, 'Un dios solitario y otros relatos', 11, 'https://narrativesarchivos.blob.core.windows.net/audios/UnDiosSolitarioYOtrosRelatos.mp3'),
(1, 'El club de los martes', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_1.mp3'),
(2, 'La casa del ídolo de Astarté', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_2.mp3'),
(3, 'Lingotes de oro', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_3.mp3'),
(4, 'Manchas de sangre', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_4.mp3'),
(5, 'Móvil versus oportunidad', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_5.mp3'),
(6, 'La huella del pulgar de san Pedro', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_6.mp3'),
(7, 'El geranio azul', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_7.mp3'),
(8, 'La señorita de compañía', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_8.mp3'),
(9, 'Los cuatro sospechosos', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_9.mp3'),
(10, 'Tragedia navideña', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_10.mp3'),
(11, 'La hierba mortal', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_11.mp3'),
(12, 'El caso del bungalow', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_12.mp3'),
(13, 'La ahogada', 12, 'https://narrativesarchivos.blob.core.windows.net/audios/MissMarpleY13Problemas_13.mp3'),
(1, 'Un escándalo en Bohemia', 13, 'https://narrativesarchivos.blob.core.windows.net/audios/UnEscandaloEnBohemia.mp3'),
(1, 'El aristócrata solterón', 14, 'https://narrativesarchivos.blob.core.windows.net/audios/ElAristocrataSolteron.mp3'),
(1, 'El misterio de Cooper Beeches', 15, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Caperucita Roja', 16, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'La ratita presumida', 17, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Los siete cabritillos y el lobo', 18, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'El gato con botas', 19, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Las hadas', 20, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Hansel y Gretel', 21, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'El piojito y la pulguita', 22, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'El gigante egoísta', 23, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'El soldadito de plomo', 24, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'La princesa y el guisante', 25, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'La vendedora de fósforos', 26, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'El último sueño del viejo roble', 27, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Los tres cerditos y el lobo', 28, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'El hombre del saco', 29, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Las tres naranjitas', 30, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
(1, 'Los ladrones arrepentidos', 31, 'https://narrativesarchivos.blob.core.windows.net/audios/ElMisterioDeCooperBeeches.mp3'),
