# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - narratives

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6144b6b73da04bb9a29b298cb5d9a4b9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b4b9f9bfef2b443981dc9bcc322f5976 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6144b6b73da04bb9a29b298cb5d9a4b9 }}/narratives:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'narratives'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_43329b0df72d420a864f5d47806d8a17 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6144b6b73da04bb9a29b298cb5d9a4b9 }}/narratives:${{ github.sha }}'